// Code generated by gen_dtypes.go; DO NOT EDIT.

package ndarray

import "strconv"

// dtypeOfStore returns the dtype of a storage slice.
func dtypeOfStore(s any) DType {
	switch s.(type) {
	case []bool:
		return Bool
	case []int8:
		return Int8
	case []int16:
		return Int16
	case []int32:
		return Int32
	case []int64:
		return Int64
	case []uint8:
		return Uint8
	case []uint16:
		return Uint16
	case []uint32:
		return Uint32
	case []uint64:
		return Uint64
	case []float32:
		return Float32
	case []complex64:
		return Complex64
	case []complex128:
		return Complex128
	}
	panic("ndarray: not a storage slice")
}

// makeStore returns a zeroed storage slice of n elements of dtype dt.
func makeStore(dt DType, n int) any {
	switch dt {
	case Bool:
		return make([]bool, n)
	case Int8:
		return make([]int8, n)
	case Int16:
		return make([]int16, n)
	case Int32:
		return make([]int32, n)
	case Int64:
		return make([]int64, n)
	case Uint8:
		return make([]uint8, n)
	case Uint16:
		return make([]uint16, n)
	case Uint32:
		return make([]uint32, n)
	case Uint64:
		return make([]uint64, n)
	case Float32:
		return make([]float32, n)
	case Float64:
		return make([]float64, n)
	case Complex64:
		return make([]complex64, n)
	case Complex128:
		return make([]complex128, n)
	}
	panic("ndarray: unknown dtype " + dt.String())
}

// storeLen returns the length of a storage slice.
func storeLen(s any) int {
	switch s := s.(type) {
	case []bool:
		return len(s)
	case []int8:
		return len(s)
	case []int16:
		return len(s)
	case []int32:
		return len(s)
	case []int64:
		return len(s)
	case []uint8:
		return len(s)
	case []uint16:
		return len(s)
	case []uint32:
		return len(s)
	case []uint64:
		return len(s)
	case []float32:
		return len(s)
	case []float64:
		return len(s)
	case []complex64:
		return len(s)
	case []complex128:
		return len(s)
	}
	panic("ndarray: not a storage slice")
}

// cloneStore returns a copy of a storage slice.
func cloneStore(s any) any {
	switch s := s.(type) {
	case []bool:
		return append([]bool(nil), s...)
	case []int8:
		return append([]int8(nil), s...)
	case []int16:
		return append([]int16(nil), s...)
	case []int32:
		return append([]int32(nil), s...)
	case []int64:
		return append([]int64(nil), s...)
	case []uint8:
		return append([]uint8(nil), s...)
	case []uint16:
		return append([]uint16(nil), s...)
	case []uint32:
		return append([]uint32(nil), s...)
	case []uint64:
		return append([]uint64(nil), s...)
	case []float32:
		return append([]float32(nil), s...)
	case []float64:
		return append([]float64(nil), s...)
	case []complex64:
		return append([]complex64(nil), s...)
	case []complex128:
		return append([]complex128(nil), s...)
	}
	panic("ndarray: not a storage slice")
}

// fillStore sets every element of dst to the single element of one, a
// storage slice of the same dtype.
func fillStore(dst, one any) {
	switch d := dst.(type) {
	case []bool:
		v := one.([]bool)[0]
		for i := range d {
			d[i] = v
		}
	case []int8:
		v := one.([]int8)[0]
		for i := range d {
			d[i] = v
		}
	case []int16:
		v := one.([]int16)[0]
		for i := range d {
			d[i] = v
		}
	case []int32:
		v := one.([]int32)[0]
		for i := range d {
			d[i] = v
		}
	case []int64:
		v := one.([]int64)[0]
		for i := range d {
			d[i] = v
		}
	case []uint8:
		v := one.([]uint8)[0]
		for i := range d {
			d[i] = v
		}
	case []uint16:
		v := one.([]uint16)[0]
		for i := range d {
			d[i] = v
		}
	case []uint32:
		v := one.([]uint32)[0]
		for i := range d {
			d[i] = v
		}
	case []uint64:
		v := one.([]uint64)[0]
		for i := range d {
			d[i] = v
		}
	case []float32:
		v := one.([]float32)[0]
		for i := range d {
			d[i] = v
		}
	case []float64:
		v := one.([]float64)[0]
		for i := range d {
			d[i] = v
		}
	case []complex64:
		v := one.([]complex64)[0]
		for i := range d {
			d[i] = v
		}
	case []complex128:
		v := one.([]complex128)[0]
		for i := range d {
			d[i] = v
		}
	}
}

// copyStore copies n elements from src[so:] to dst[do:], two storage slices
// of the same dtype.
func copyStore(dst any, do int, src any, so, n int) {
	switch d := dst.(type) {
	case []bool:
		copy(d[do:do+n], src.([]bool)[so:so+n])
	case []int8:
		copy(d[do:do+n], src.([]int8)[so:so+n])
	case []int16:
		copy(d[do:do+n], src.([]int16)[so:so+n])
	case []int32:
		copy(d[do:do+n], src.([]int32)[so:so+n])
	case []int64:
		copy(d[do:do+n], src.([]int64)[so:so+n])
	case []uint8:
		copy(d[do:do+n], src.([]uint8)[so:so+n])
	case []uint16:
		copy(d[do:do+n], src.([]uint16)[so:so+n])
	case []uint32:
		copy(d[do:do+n], src.([]uint32)[so:so+n])
	case []uint64:
		copy(d[do:do+n], src.([]uint64)[so:so+n])
	case []float32:
		copy(d[do:do+n], src.([]float32)[so:so+n])
	case []float64:
		copy(d[do:do+n], src.([]float64)[so:so+n])
	case []complex64:
		copy(d[do:do+n], src.([]complex64)[so:so+n])
	case []complex128:
		copy(d[do:do+n], src.([]complex128)[so:so+n])
	}
}

// takeStore returns the elements of a storage slice at the given positions.
func takeStore(s any, idx []int) any {
	switch s := s.(type) {
	case []bool:
		out := make([]bool, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	case []int8:
		out := make([]int8, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	case []int16:
		out := make([]int16, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	case []int32:
		out := make([]int32, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	case []int64:
		out := make([]int64, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	case []uint8:
		out := make([]uint8, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	case []uint16:
		out := make([]uint16, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	case []uint32:
		out := make([]uint32, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	case []uint64:
		out := make([]uint64, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	case []float32:
		out := make([]float32, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	case []float64:
		out := make([]float64, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	case []complex64:
		out := make([]complex64, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	case []complex128:
		out := make([]complex128, len(idx))
		for k, i := range idx {
			out[k] = s[i]
		}
		return out
	}
	panic("ndarray: not a storage slice")
}

// gatherStore returns a contiguous copy of the elements of the view a.
func gatherStore(a *Array) any {
	switch s := a.store().(type) {
	case []bool:
		return gather(s, a.shape, a.strides, a.offset)
	case []int8:
		return gather(s, a.shape, a.strides, a.offset)
	case []int16:
		return gather(s, a.shape, a.strides, a.offset)
	case []int32:
		return gather(s, a.shape, a.strides, a.offset)
	case []int64:
		return gather(s, a.shape, a.strides, a.offset)
	case []uint8:
		return gather(s, a.shape, a.strides, a.offset)
	case []uint16:
		return gather(s, a.shape, a.strides, a.offset)
	case []uint32:
		return gather(s, a.shape, a.strides, a.offset)
	case []uint64:
		return gather(s, a.shape, a.strides, a.offset)
	case []float32:
		return gather(s, a.shape, a.strides, a.offset)
	case []complex64:
		return gather(s, a.shape, a.strides, a.offset)
	case []complex128:
		return gather(s, a.shape, a.strides, a.offset)
	}
	panic("ndarray: not a storage slice")
}

// broadcastStore returns a contiguous copy of a's elements broadcast to shape.
func broadcastStore(a *Array, shape []int) any {
	es := a.broadcastStrides(shape)
	switch s := a.store().(type) {
	case []bool:
		return gather(s, shape, es, a.offset)
	case []int8:
		return gather(s, shape, es, a.offset)
	case []int16:
		return gather(s, shape, es, a.offset)
	case []int32:
		return gather(s, shape, es, a.offset)
	case []int64:
		return gather(s, shape, es, a.offset)
	case []uint8:
		return gather(s, shape, es, a.offset)
	case []uint16:
		return gather(s, shape, es, a.offset)
	case []uint32:
		return gather(s, shape, es, a.offset)
	case []uint64:
		return gather(s, shape, es, a.offset)
	case []float32:
		return gather(s, shape, es, a.offset)
	case []float64:
		return gather(s, shape, es, a.offset)
	case []complex64:
		return gather(s, shape, es, a.offset)
	case []complex128:
		return gather(s, shape, es, a.offset)
	}
	panic("ndarray: not a storage slice")
}

// convertStore converts every element of src into dst, two storage slices
// of the same length, as AsType documents.
func convertStore(dst, src any) {
	switch s := src.(type) {
	case []bool:
		switch d := dst.(type) {
		case []bool:
			copy(d, s)
		case []int8:
			for i, v := range s {
				d[i] = boolTo[int8](v)
			}
		case []int16:
			for i, v := range s {
				d[i] = boolTo[int16](v)
			}
		case []int32:
			for i, v := range s {
				d[i] = boolTo[int32](v)
			}
		case []int64:
			for i, v := range s {
				d[i] = boolTo[int64](v)
			}
		case []uint8:
			for i, v := range s {
				d[i] = boolTo[uint8](v)
			}
		case []uint16:
			for i, v := range s {
				d[i] = boolTo[uint16](v)
			}
		case []uint32:
			for i, v := range s {
				d[i] = boolTo[uint32](v)
			}
		case []uint64:
			for i, v := range s {
				d[i] = boolTo[uint64](v)
			}
		case []float32:
			for i, v := range s {
				d[i] = boolTo[float32](v)
			}
		case []float64:
			for i, v := range s {
				d[i] = boolTo[float64](v)
			}
		case []complex64:
			for i, v := range s {
				d[i] = boolTo[complex64](v)
			}
		case []complex128:
			for i, v := range s {
				d[i] = boolTo[complex128](v)
			}
		}
	case []int8:
		switch d := dst.(type) {
		case []bool:
			for i, v := range s {
				d[i] = v != 0
			}
		case []int8:
			copy(d, s)
		case []int16:
			for i, v := range s {
				d[i] = int16(v)
			}
		case []int32:
			for i, v := range s {
				d[i] = int32(v)
			}
		case []int64:
			for i, v := range s {
				d[i] = int64(v)
			}
		case []uint8:
			for i, v := range s {
				d[i] = uint8(v)
			}
		case []uint16:
			for i, v := range s {
				d[i] = uint16(v)
			}
		case []uint32:
			for i, v := range s {
				d[i] = uint32(v)
			}
		case []uint64:
			for i, v := range s {
				d[i] = uint64(v)
			}
		case []float32:
			for i, v := range s {
				d[i] = float32(v)
			}
		case []float64:
			for i, v := range s {
				d[i] = float64(v)
			}
		case []complex64:
			for i, v := range s {
				d[i] = complex64(complex(float64(v), 0))
			}
		case []complex128:
			for i, v := range s {
				d[i] = complex128(complex(float64(v), 0))
			}
		}
	case []int16:
		switch d := dst.(type) {
		case []bool:
			for i, v := range s {
				d[i] = v != 0
			}
		case []int8:
			for i, v := range s {
				d[i] = int8(v)
			}
		case []int16:
			copy(d, s)
		case []int32:
			for i, v := range s {
				d[i] = int32(v)
			}
		case []int64:
			for i, v := range s {
				d[i] = int64(v)
			}
		case []uint8:
			for i, v := range s {
				d[i] = uint8(v)
			}
		case []uint16:
			for i, v := range s {
				d[i] = uint16(v)
			}
		case []uint32:
			for i, v := range s {
				d[i] = uint32(v)
			}
		case []uint64:
			for i, v := range s {
				d[i] = uint64(v)
			}
		case []float32:
			for i, v := range s {
				d[i] = float32(v)
			}
		case []float64:
			for i, v := range s {
				d[i] = float64(v)
			}
		case []complex64:
			for i, v := range s {
				d[i] = complex64(complex(float64(v), 0))
			}
		case []complex128:
			for i, v := range s {
				d[i] = complex128(complex(float64(v), 0))
			}
		}
	case []int32:
		switch d := dst.(type) {
		case []bool:
			for i, v := range s {
				d[i] = v != 0
			}
		case []int8:
			for i, v := range s {
				d[i] = int8(v)
			}
		case []int16:
			for i, v := range s {
				d[i] = int16(v)
			}
		case []int32:
			copy(d, s)
		case []int64:
			for i, v := range s {
				d[i] = int64(v)
			}
		case []uint8:
			for i, v := range s {
				d[i] = uint8(v)
			}
		case []uint16:
			for i, v := range s {
				d[i] = uint16(v)
			}
		case []uint32:
			for i, v := range s {
				d[i] = uint32(v)
			}
		case []uint64:
			for i, v := range s {
				d[i] = uint64(v)
			}
		case []float32:
			for i, v := range s {
				d[i] = float32(v)
			}
		case []float64:
			for i, v := range s {
				d[i] = float64(v)
			}
		case []complex64:
			for i, v := range s {
				d[i] = complex64(complex(float64(v), 0))
			}
		case []complex128:
			for i, v := range s {
				d[i] = complex128(complex(float64(v), 0))
			}
		}
	case []int64:
		switch d := dst.(type) {
		case []bool:
			for i, v := range s {
				d[i] = v != 0
			}
		case []int8:
			for i, v := range s {
				d[i] = int8(v)
			}
		case []int16:
			for i, v := range s {
				d[i] = int16(v)
			}
		case []int32:
			for i, v := range s {
				d[i] = int32(v)
			}
		case []int64:
			copy(d, s)
		case []uint8:
			for i, v := range s {
				d[i] = uint8(v)
			}
		case []uint16:
			for i, v := range s {
				d[i] = uint16(v)
			}
		case []uint32:
			for i, v := range s {
				d[i] = uint32(v)
			}
		case []uint64:
			for i, v := range s {
				d[i] = uint64(v)
			}
		case []float32:
			for i, v := range s {
				d[i] = float32(v)
			}
		case []float64:
			for i, v := range s {
				d[i] = float64(v)
			}
		case []complex64:
			for i, v := range s {
				d[i] = complex64(complex(float64(v), 0))
			}
		case []complex128:
			for i, v := range s {
				d[i] = complex128(complex(float64(v), 0))
			}
		}
	case []uint8:
		switch d := dst.(type) {
		case []bool:
			for i, v := range s {
				d[i] = v != 0
			}
		case []int8:
			for i, v := range s {
				d[i] = int8(v)
			}
		case []int16:
			for i, v := range s {
				d[i] = int16(v)
			}
		case []int32:
			for i, v := range s {
				d[i] = int32(v)
			}
		case []int64:
			for i, v := range s {
				d[i] = int64(v)
			}
		case []uint8:
			copy(d, s)
		case []uint16:
			for i, v := range s {
				d[i] = uint16(v)
			}
		case []uint32:
			for i, v := range s {
				d[i] = uint32(v)
			}
		case []uint64:
			for i, v := range s {
				d[i] = uint64(v)
			}
		case []float32:
			for i, v := range s {
				d[i] = float32(v)
			}
		case []float64:
			for i, v := range s {
				d[i] = float64(v)
			}
		case []complex64:
			for i, v := range s {
				d[i] = complex64(complex(float64(v), 0))
			}
		case []complex128:
			for i, v := range s {
				d[i] = complex128(complex(float64(v), 0))
			}
		}
	case []uint16:
		switch d := dst.(type) {
		case []bool:
			for i, v := range s {
				d[i] = v != 0
			}
		case []int8:
			for i, v := range s {
				d[i] = int8(v)
			}
		case []int16:
			for i, v := range s {
				d[i] = int16(v)
			}
		case []int32:
			for i, v := range s {
				d[i] = int32(v)
			}
		case []int64:
			for i, v := range s {
				d[i] = int64(v)
			}
		case []uint8:
			for i, v := range s {
				d[i] = uint8(v)
			}
		case []uint16:
			copy(d, s)
		case []uint32:
			for i, v := range s {
				d[i] = uint32(v)
			}
		case []uint64:
			for i, v := range s {
				d[i] = uint64(v)
			}
		case []float32:
			for i, v := range s {
				d[i] = float32(v)
			}
		case []float64:
			for i, v := range s {
				d[i] = float64(v)
			}
		case []complex64:
			for i, v := range s {
				d[i] = complex64(complex(float64(v), 0))
			}
		case []complex128:
			for i, v := range s {
				d[i] = complex128(complex(float64(v), 0))
			}
		}
	case []uint32:
		switch d := dst.(type) {
		case []bool:
			for i, v := range s {
				d[i] = v != 0
			}
		case []int8:
			for i, v := range s {
				d[i] = int8(v)
			}
		case []int16:
			for i, v := range s {
				d[i] = int16(v)
			}
		case []int32:
			for i, v := range s {
				d[i] = int32(v)
			}
		case []int64:
			for i, v := range s {
				d[i] = int64(v)
			}
		case []uint8:
			for i, v := range s {
				d[i] = uint8(v)
			}
		case []uint16:
			for i, v := range s {
				d[i] = uint16(v)
			}
		case []uint32:
			copy(d, s)
		case []uint64:
			for i, v := range s {
				d[i] = uint64(v)
			}
		case []float32:
			for i, v := range s {
				d[i] = float32(v)
			}
		case []float64:
			for i, v := range s {
				d[i] = float64(v)
			}
		case []complex64:
			for i, v := range s {
				d[i] = complex64(complex(float64(v), 0))
			}
		case []complex128:
			for i, v := range s {
				d[i] = complex128(complex(float64(v), 0))
			}
		}
	case []uint64:
		switch d := dst.(type) {
		case []bool:
			for i, v := range s {
				d[i] = v != 0
			}
		case []int8:
			for i, v := range s {
				d[i] = int8(v)
			}
		case []int16:
			for i, v := range s {
				d[i] = int16(v)
			}
		case []int32:
			for i, v := range s {
				d[i] = int32(v)
			}
		case []int64:
			for i, v := range s {
				d[i] = int64(v)
			}
		case []uint8:
			for i, v := range s {
				d[i] = uint8(v)
			}
		case []uint16:
			for i, v := range s {
				d[i] = uint16(v)
			}
		case []uint32:
			for i, v := range s {
				d[i] = uint32(v)
			}
		case []uint64:
			copy(d, s)
		case []float32:
			for i, v := range s {
				d[i] = float32(v)
			}
		case []float64:
			for i, v := range s {
				d[i] = float64(v)
			}
		case []complex64:
			for i, v := range s {
				d[i] = complex64(complex(float64(v), 0))
			}
		case []complex128:
			for i, v := range s {
				d[i] = complex128(complex(float64(v), 0))
			}
		}
	case []float32:
		switch d := dst.(type) {
		case []bool:
			for i, v := range s {
				d[i] = v != 0
			}
		case []int8:
			for i, v := range s {
				d[i] = satInt[int8](float64(v))
			}
		case []int16:
			for i, v := range s {
				d[i] = satInt[int16](float64(v))
			}
		case []int32:
			for i, v := range s {
				d[i] = satInt[int32](float64(v))
			}
		case []int64:
			for i, v := range s {
				d[i] = satInt[int64](float64(v))
			}
		case []uint8:
			for i, v := range s {
				d[i] = satInt[uint8](float64(v))
			}
		case []uint16:
			for i, v := range s {
				d[i] = satInt[uint16](float64(v))
			}
		case []uint32:
			for i, v := range s {
				d[i] = satInt[uint32](float64(v))
			}
		case []uint64:
			for i, v := range s {
				d[i] = satInt[uint64](float64(v))
			}
		case []float32:
			copy(d, s)
		case []float64:
			for i, v := range s {
				d[i] = float64(v)
			}
		case []complex64:
			for i, v := range s {
				d[i] = complex64(complex(float64(v), 0))
			}
		case []complex128:
			for i, v := range s {
				d[i] = complex128(complex(float64(v), 0))
			}
		}
	case []float64:
		switch d := dst.(type) {
		case []bool:
			for i, v := range s {
				d[i] = v != 0
			}
		case []int8:
			for i, v := range s {
				d[i] = satInt[int8](float64(v))
			}
		case []int16:
			for i, v := range s {
				d[i] = satInt[int16](float64(v))
			}
		case []int32:
			for i, v := range s {
				d[i] = satInt[int32](float64(v))
			}
		case []int64:
			for i, v := range s {
				d[i] = satInt[int64](float64(v))
			}
		case []uint8:
			for i, v := range s {
				d[i] = satInt[uint8](float64(v))
			}
		case []uint16:
			for i, v := range s {
				d[i] = satInt[uint16](float64(v))
			}
		case []uint32:
			for i, v := range s {
				d[i] = satInt[uint32](float64(v))
			}
		case []uint64:
			for i, v := range s {
				d[i] = satInt[uint64](float64(v))
			}
		case []float32:
			for i, v := range s {
				d[i] = float32(v)
			}
		case []float64:
			copy(d, s)
		case []complex64:
			for i, v := range s {
				d[i] = complex64(complex(float64(v), 0))
			}
		case []complex128:
			for i, v := range s {
				d[i] = complex128(complex(float64(v), 0))
			}
		}
	case []complex64:
		switch d := dst.(type) {
		case []bool:
			for i, v := range s {
				d[i] = v != 0
			}
		case []int8:
			for i, v := range s {
				d[i] = satInt[int8](float64(float64(real(v))))
			}
		case []int16:
			for i, v := range s {
				d[i] = satInt[int16](float64(float64(real(v))))
			}
		case []int32:
			for i, v := range s {
				d[i] = satInt[int32](float64(float64(real(v))))
			}
		case []int64:
			for i, v := range s {
				d[i] = satInt[int64](float64(float64(real(v))))
			}
		case []uint8:
			for i, v := range s {
				d[i] = satInt[uint8](float64(float64(real(v))))
			}
		case []uint16:
			for i, v := range s {
				d[i] = satInt[uint16](float64(float64(real(v))))
			}
		case []uint32:
			for i, v := range s {
				d[i] = satInt[uint32](float64(float64(real(v))))
			}
		case []uint64:
			for i, v := range s {
				d[i] = satInt[uint64](float64(float64(real(v))))
			}
		case []float32:
			for i, v := range s {
				d[i] = float32(float64(real(v)))
			}
		case []float64:
			for i, v := range s {
				d[i] = float64(real(v))
			}
		case []complex64:
			copy(d, s)
		case []complex128:
			for i, v := range s {
				d[i] = complex128(v)
			}
		}
	case []complex128:
		switch d := dst.(type) {
		case []bool:
			for i, v := range s {
				d[i] = v != 0
			}
		case []int8:
			for i, v := range s {
				d[i] = satInt[int8](float64(float64(real(v))))
			}
		case []int16:
			for i, v := range s {
				d[i] = satInt[int16](float64(float64(real(v))))
			}
		case []int32:
			for i, v := range s {
				d[i] = satInt[int32](float64(float64(real(v))))
			}
		case []int64:
			for i, v := range s {
				d[i] = satInt[int64](float64(float64(real(v))))
			}
		case []uint8:
			for i, v := range s {
				d[i] = satInt[uint8](float64(float64(real(v))))
			}
		case []uint16:
			for i, v := range s {
				d[i] = satInt[uint16](float64(float64(real(v))))
			}
		case []uint32:
			for i, v := range s {
				d[i] = satInt[uint32](float64(float64(real(v))))
			}
		case []uint64:
			for i, v := range s {
				d[i] = satInt[uint64](float64(float64(real(v))))
			}
		case []float32:
			for i, v := range s {
				d[i] = float32(float64(real(v)))
			}
		case []float64:
			for i, v := range s {
				d[i] = float64(real(v))
			}
		case []complex64:
			for i, v := range s {
				d[i] = complex64(v)
			}
		case []complex128:
			copy(d, s)
		}
	}
}

// elemComplex returns element i of a storage slice as a complex128.
func elemComplex(s any, i int) complex128 {
	switch s := s.(type) {
	case []bool:
		return boolTo[complex128](s[i])
	case []int8:
		return complex128(complex(float64(s[i]), 0))
	case []int16:
		return complex128(complex(float64(s[i]), 0))
	case []int32:
		return complex128(complex(float64(s[i]), 0))
	case []int64:
		return complex128(complex(float64(s[i]), 0))
	case []uint8:
		return complex128(complex(float64(s[i]), 0))
	case []uint16:
		return complex128(complex(float64(s[i]), 0))
	case []uint32:
		return complex128(complex(float64(s[i]), 0))
	case []uint64:
		return complex128(complex(float64(s[i]), 0))
	case []float32:
		return complex128(complex(float64(s[i]), 0))
	case []float64:
		return complex128(complex(float64(s[i]), 0))
	case []complex64:
		return complex128(s[i])
	case []complex128:
		return s[i]
	}
	panic("ndarray: not a storage slice")
}

// setComplex stores v, converted, as element i of a storage slice.
func setComplex(s any, i int, v complex128) {
	switch s := s.(type) {
	case []bool:
		s[i] = v != 0
	case []int8:
		s[i] = satInt[int8](float64(float64(real(v))))
	case []int16:
		s[i] = satInt[int16](float64(float64(real(v))))
	case []int32:
		s[i] = satInt[int32](float64(float64(real(v))))
	case []int64:
		s[i] = satInt[int64](float64(float64(real(v))))
	case []uint8:
		s[i] = satInt[uint8](float64(float64(real(v))))
	case []uint16:
		s[i] = satInt[uint16](float64(float64(real(v))))
	case []uint32:
		s[i] = satInt[uint32](float64(float64(real(v))))
	case []uint64:
		s[i] = satInt[uint64](float64(float64(real(v))))
	case []float32:
		s[i] = float32(float64(real(v)))
	case []float64:
		s[i] = float64(real(v))
	case []complex64:
		s[i] = complex64(v)
	case []complex128:
		s[i] = v
	}
}

// elemFloat returns element i of a storage slice of a real dtype as a float64.
func elemFloat(s any, i int) float64 {
	switch s := s.(type) {
	case []bool:
		return boolTo[float64](s[i])
	case []int8:
		return float64(s[i])
	case []int16:
		return float64(s[i])
	case []int32:
		return float64(s[i])
	case []int64:
		return float64(s[i])
	case []uint8:
		return float64(s[i])
	case []uint16:
		return float64(s[i])
	case []uint32:
		return float64(s[i])
	case []uint64:
		return float64(s[i])
	case []float32:
		return float64(s[i])
	}
	panic("ndarray: complex element read as float64; use AtComplex")
}

// setFloat stores v, converted, as element i of a storage slice.
func setFloat(s any, i int, v float64) {
	switch s := s.(type) {
	case []bool:
		s[i] = v != 0
	case []int8:
		s[i] = satInt[int8](float64(v))
	case []int16:
		s[i] = satInt[int16](float64(v))
	case []int32:
		s[i] = satInt[int32](float64(v))
	case []int64:
		s[i] = satInt[int64](float64(v))
	case []uint8:
		s[i] = satInt[uint8](float64(v))
	case []uint16:
		s[i] = satInt[uint16](float64(v))
	case []uint32:
		s[i] = satInt[uint32](float64(v))
	case []uint64:
		s[i] = satInt[uint64](float64(v))
	case []float32:
		s[i] = float32(v)
	case []complex64:
		s[i] = complex64(complex(float64(v), 0))
	case []complex128:
		s[i] = complex128(complex(float64(v), 0))
	}
}

// elemString formats element i of a storage slice as NumPy prints it.
func elemString(s any, i int) string {
	switch s := s.(type) {
	case []bool:
		if s[i] {
			return "true"
		}
		return "false"
	case []int8:
		return strconv.FormatInt(int64(s[i]), 10)
	case []int16:
		return strconv.FormatInt(int64(s[i]), 10)
	case []int32:
		return strconv.FormatInt(int64(s[i]), 10)
	case []int64:
		return strconv.FormatInt(int64(s[i]), 10)
	case []uint8:
		return strconv.FormatUint(uint64(s[i]), 10)
	case []uint16:
		return strconv.FormatUint(uint64(s[i]), 10)
	case []uint32:
		return strconv.FormatUint(uint64(s[i]), 10)
	case []uint64:
		return strconv.FormatUint(uint64(s[i]), 10)
	case []float32:
		return floatString(float64(s[i]), 32)
	case []float64:
		return floatString(float64(s[i]), 64)
	case []complex64:
		return complexString(complex128(s[i]), 32)
	case []complex128:
		return complexString(complex128(s[i]), 64)
	}
	panic("ndarray: not a storage slice")
}

// arithStore applies a binary operation to storage slices of one dtype.
func arithStore(op binCode, d, x, y any) {
	switch d := d.(type) {
	case []int8:
		binInt(op, d, x.([]int8), y.([]int8))
	case []int16:
		binInt(op, d, x.([]int16), y.([]int16))
	case []int32:
		binInt(op, d, x.([]int32), y.([]int32))
	case []int64:
		binInt(op, d, x.([]int64), y.([]int64))
	case []uint8:
		binInt(op, d, x.([]uint8), y.([]uint8))
	case []uint16:
		binInt(op, d, x.([]uint16), y.([]uint16))
	case []uint32:
		binInt(op, d, x.([]uint32), y.([]uint32))
	case []uint64:
		binInt(op, d, x.([]uint64), y.([]uint64))
	case []float32:
		binFloat(op, d, x.([]float32), y.([]float32))
	case []complex64:
		binComplex(op, d, x.([]complex64), y.([]complex64))
	case []complex128:
		binComplex(op, d, x.([]complex128), y.([]complex128))
	case []bool:
		binBool(op, d, x.([]bool), y.([]bool))
	}
}

// cmpStore compares storage slices of one dtype into d.
func cmpStore(op cmpCode, d []bool, x, y any) {
	switch x := x.(type) {
	case []int8:
		cmpOrdered(op, d, x, y.([]int8))
	case []int16:
		cmpOrdered(op, d, x, y.([]int16))
	case []int32:
		cmpOrdered(op, d, x, y.([]int32))
	case []int64:
		cmpOrdered(op, d, x, y.([]int64))
	case []uint8:
		cmpOrdered(op, d, x, y.([]uint8))
	case []uint16:
		cmpOrdered(op, d, x, y.([]uint16))
	case []uint32:
		cmpOrdered(op, d, x, y.([]uint32))
	case []uint64:
		cmpOrdered(op, d, x, y.([]uint64))
	case []float32:
		cmpOrdered(op, d, x, y.([]float32))
	case []float64:
		cmpOrdered(op, d, x, y.([]float64))
	case []complex64:
		cmpComplex(op, d, x, y.([]complex64))
	case []complex128:
		cmpComplex(op, d, x, y.([]complex128))
	case []bool:
		cmpBool(op, d, x, y.([]bool))
	}
}

// accumulateStore sums or multiplies src along the middle axis of
// [outer][axisLen][inner] into dst; both have an accumulation dtype.
func accumulateStore(op reduceCode, dst, src any, outer, axisLen, inner int) {
	switch d := dst.(type) {
	case []int64:
		reduceNum(op, d, src.([]int64), outer, axisLen, inner)
	case []uint64:
		reduceNum(op, d, src.([]uint64), outer, axisLen, inner)
	case []float32:
		reduceNum(op, d, src.([]float32), outer, axisLen, inner)
	case []complex64:
		reduceNum(op, d, src.([]complex64), outer, axisLen, inner)
	case []complex128:
		reduceNum(op, d, src.([]complex128), outer, axisLen, inner)
	}
}

// extremeStore takes the maximum or minimum of src along the middle axis.
func extremeStore(op reduceCode, dst, src any, outer, axisLen, inner int) {
	switch d := dst.(type) {
	case []int8:
		reduceOrdered(op, d, src.([]int8), outer, axisLen, inner)
	case []int16:
		reduceOrdered(op, d, src.([]int16), outer, axisLen, inner)
	case []int32:
		reduceOrdered(op, d, src.([]int32), outer, axisLen, inner)
	case []int64:
		reduceOrdered(op, d, src.([]int64), outer, axisLen, inner)
	case []uint8:
		reduceOrdered(op, d, src.([]uint8), outer, axisLen, inner)
	case []uint16:
		reduceOrdered(op, d, src.([]uint16), outer, axisLen, inner)
	case []uint32:
		reduceOrdered(op, d, src.([]uint32), outer, axisLen, inner)
	case []uint64:
		reduceOrdered(op, d, src.([]uint64), outer, axisLen, inner)
	case []float32:
		reduceOrdered(op, d, src.([]float32), outer, axisLen, inner)
	case []complex64:
		reduceComplex(op, d, src.([]complex64), outer, axisLen, inner)
	case []complex128:
		reduceComplex(op, d, src.([]complex128), outer, axisLen, inner)
	case []bool:
		reduceBool(op, d, src.([]bool), outer, axisLen, inner)
	}
}

// argStore writes the arg-max (or arg-min) along the middle axis into dst.
func argStore(larger bool, dst []int64, src any, outer, axisLen, inner int) {
	switch s := src.(type) {
	case []int8:
		argOrdered(larger, dst, s, outer, axisLen, inner)
	case []int16:
		argOrdered(larger, dst, s, outer, axisLen, inner)
	case []int32:
		argOrdered(larger, dst, s, outer, axisLen, inner)
	case []int64:
		argOrdered(larger, dst, s, outer, axisLen, inner)
	case []uint8:
		argOrdered(larger, dst, s, outer, axisLen, inner)
	case []uint16:
		argOrdered(larger, dst, s, outer, axisLen, inner)
	case []uint32:
		argOrdered(larger, dst, s, outer, axisLen, inner)
	case []uint64:
		argOrdered(larger, dst, s, outer, axisLen, inner)
	case []float32:
		argOrdered(larger, dst, s, outer, axisLen, inner)
	case []float64:
		argOrdered(larger, dst, s, outer, axisLen, inner)
	case []complex64:
		argComplex(larger, dst, s, outer, axisLen, inner)
	case []complex128:
		argComplex(larger, dst, s, outer, axisLen, inner)
	case []bool:
		argBool(larger, dst, s, outer, axisLen, inner)
	}
}

// scanStore is the cumulative sum or product along the middle axis.
func scanStore(op reduceCode, dst, src any, outer, axisLen, inner int) {
	switch d := dst.(type) {
	case []int64:
		scanNum(op, d, src.([]int64), outer, axisLen, inner)
	case []uint64:
		scanNum(op, d, src.([]uint64), outer, axisLen, inner)
	case []float32:
		scanNum(op, d, src.([]float32), outer, axisLen, inner)
	case []complex64:
		scanNum(op, d, src.([]complex64), outer, axisLen, inner)
	case []complex128:
		scanNum(op, d, src.([]complex128), outer, axisLen, inner)
	}
}

// whereStore picks from t where c is true and from f elsewhere.
func whereStore(d any, c []bool, t, f any) {
	switch d := d.(type) {
	case []bool:
		whereT(d, c, t.([]bool), f.([]bool))
	case []int8:
		whereT(d, c, t.([]int8), f.([]int8))
	case []int16:
		whereT(d, c, t.([]int16), f.([]int16))
	case []int32:
		whereT(d, c, t.([]int32), f.([]int32))
	case []int64:
		whereT(d, c, t.([]int64), f.([]int64))
	case []uint8:
		whereT(d, c, t.([]uint8), f.([]uint8))
	case []uint16:
		whereT(d, c, t.([]uint16), f.([]uint16))
	case []uint32:
		whereT(d, c, t.([]uint32), f.([]uint32))
	case []uint64:
		whereT(d, c, t.([]uint64), f.([]uint64))
	case []float32:
		whereT(d, c, t.([]float32), f.([]float32))
	case []float64:
		whereT(d, c, t.([]float64), f.([]float64))
	case []complex64:
		whereT(d, c, t.([]complex64), f.([]complex64))
	case []complex128:
		whereT(d, c, t.([]complex128), f.([]complex128))
	}
}

// intUnaryStore negates, takes the absolute value of, or squares integers.
func intUnaryStore(code unaryCode, d, x any) {
	switch d := d.(type) {
	case []int8:
		s := x.([]int8)
		switch code {
		case uNeg:
			negInt(d, s)
		case uAbs:
			absInt(d, s)
		default:
			squareInt(d, s)
		}
	case []int16:
		s := x.([]int16)
		switch code {
		case uNeg:
			negInt(d, s)
		case uAbs:
			absInt(d, s)
		default:
			squareInt(d, s)
		}
	case []int32:
		s := x.([]int32)
		switch code {
		case uNeg:
			negInt(d, s)
		case uAbs:
			absInt(d, s)
		default:
			squareInt(d, s)
		}
	case []int64:
		s := x.([]int64)
		switch code {
		case uNeg:
			negInt(d, s)
		case uAbs:
			absInt(d, s)
		default:
			squareInt(d, s)
		}
	case []uint8:
		s := x.([]uint8)
		switch code {
		case uNeg:
			negInt(d, s)
		case uAbs:
			absInt(d, s)
		default:
			squareInt(d, s)
		}
	case []uint16:
		s := x.([]uint16)
		switch code {
		case uNeg:
			negInt(d, s)
		case uAbs:
			absInt(d, s)
		default:
			squareInt(d, s)
		}
	case []uint32:
		s := x.([]uint32)
		switch code {
		case uNeg:
			negInt(d, s)
		case uAbs:
			absInt(d, s)
		default:
			squareInt(d, s)
		}
	case []uint64:
		s := x.([]uint64)
		switch code {
		case uNeg:
			negInt(d, s)
		case uAbs:
			absInt(d, s)
		default:
			squareInt(d, s)
		}
	}
}

// matmulStore multiplies (m x k) by (k x n) storage slices of one dtype into d.
func matmulStore(d, x, y any, m, k, n int) {
	switch d := d.(type) {
	case []int8:
		matmulNum(d, x.([]int8), y.([]int8), m, k, n)
	case []int16:
		matmulNum(d, x.([]int16), y.([]int16), m, k, n)
	case []int32:
		matmulNum(d, x.([]int32), y.([]int32), m, k, n)
	case []int64:
		matmulNum(d, x.([]int64), y.([]int64), m, k, n)
	case []uint8:
		matmulNum(d, x.([]uint8), y.([]uint8), m, k, n)
	case []uint16:
		matmulNum(d, x.([]uint16), y.([]uint16), m, k, n)
	case []uint32:
		matmulNum(d, x.([]uint32), y.([]uint32), m, k, n)
	case []uint64:
		matmulNum(d, x.([]uint64), y.([]uint64), m, k, n)
	case []float32:
		matmulNum(d, x.([]float32), y.([]float32), m, k, n)
	case []complex64:
		matmulNum(d, x.([]complex64), y.([]complex64), m, k, n)
	case []complex128:
		matmulNum(d, x.([]complex128), y.([]complex128), m, k, n)
	case []bool:
		matmulBool(d, x.([]bool), y.([]bool), m, k, n)
	}
}
