package fft

import (
	_ "embed"
	"encoding/json"
	"errors"
	"math"
	"strconv"
	"testing"

	"github.com/go-ndarray/ndarray"
)

// cases.json holds numpy.fft's results for every transform on several
// dtypes, shapes and argument sets, generated by testdata/cases.py.
//
//go:embed testdata/cases.json
var casesJSON []byte

type fftCase struct {
	Fn     string            `json:"fn"`
	DType  string            `json:"dtype"`
	Shape  []int             `json:"shape"`
	X      []json.RawMessage `json:"x"`
	N      *int              `json:"n"`
	S      []int             `json:"s"`
	Axis   *int              `json:"axis"`
	Axes   []int             `json:"axes"`
	Norm   *string           `json:"norm"`
	RDType string            `json:"rdtype"`
	RShape []int             `json:"rshape"`
	R      []json.RawMessage `json:"r"`
	Error  string            `json:"error"`
}

func parseValues(t *testing.T, raw []json.RawMessage) []complex128 {
	t.Helper()
	out := make([]complex128, len(raw))
	for i, r := range raw {
		var pair []string
		if json.Unmarshal(r, &pair) == nil {
			out[i] = complex(num(t, pair[0]), num(t, pair[1]))
			continue
		}
		var s string
		if err := json.Unmarshal(r, &s); err != nil {
			t.Fatal(err)
		}
		out[i] = complex(num(t, s), 0)
	}
	return out
}

func num(t *testing.T, s string) float64 {
	t.Helper()
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		t.Fatal(err)
	}
	return f
}

var norms = map[string]Norm{"ortho": Ortho, "forward": Forward, "backward": Backward}

type transform func(*ndarray.Array, Options) (*ndarray.Array, error)

var transforms = map[string]transform{
	"fft": FFTWith, "ifft": IFFTWith, "rfft": RFFTWith, "irfft": IRFFTWith,
	"hfft": HFFTWith, "ihfft": IHFFTWith,
	"fft2": FFT2With, "ifft2": IFFT2With, "rfft2": RFFT2With, "irfft2": IRFFT2With,
	"fftn": FFTNWith, "ifftn": IFFTNWith, "rfftn": RFFTNWith, "irfftn": IRFFTNWith,
}

// TestMatchesNumPy runs every case of the fixture and compares dtype, shape
// and values (within 64 epsilons of the largest magnitude of the result, in
// the result's precision: the two libraries use different algorithms).
func TestMatchesNumPy(t *testing.T) {
	var fx struct {
		NumPy string    `json:"numpy"`
		Cases []fftCase `json:"cases"`
	}
	if err := json.Unmarshal(casesJSON, &fx); err != nil {
		t.Fatal(err)
	}
	checked := 0
	for i, c := range fx.Cases {
		got, err := runCase(t, c)
		if c.Error != "" {
			if err == nil {
				t.Errorf("case %d %s %s %v: got %v, NumPy raises %s", i, c.Fn, c.DType, c.Shape, got.Shape(), c.Error)
			}
			continue
		}
		if err != nil {
			t.Errorf("case %d %s %s %v: %v", i, c.Fn, c.DType, c.Shape, err)
			continue
		}
		if got.DType().String() != c.RDType || !sameInts(got.Shape(), c.RShape) {
			t.Errorf("case %d %s %s %v: %v %v, NumPy %s %v", i, c.Fn, c.DType, c.Shape,
				got.DType(), got.Shape(), c.RDType, c.RShape)
			continue
		}
		want := parseValues(t, c.R)
		gc := got.AsType(ndarray.Complex128)
		g, _ := ndarray.Data[complex128](gc)
		scale := 0.0
		for _, w := range want {
			scale = math.Max(scale, math.Hypot(real(w), imag(w)))
		}
		eps := 0x1p-52
		if c.RDType == "complex64" || c.RDType == "float32" {
			eps = 0x1p-23
		}
		for j := range want {
			d := g[j] - want[j]
			if math.Hypot(real(d), imag(d)) > 64*eps*math.Max(scale, 1) {
				t.Errorf("case %d %s %s %v [%d] = %v, NumPy %v", i, c.Fn, c.DType, c.Shape, j, g[j], want[j])
				break
			}
		}
		checked++
	}
	t.Logf("%d of %d cases checked against NumPy %s", checked, len(fx.Cases), fx.NumPy)
}

func sameInts(a, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// runCase builds the input of a case and calls the matching function.
func runCase(t *testing.T, c fftCase) (*ndarray.Array, error) {
	t.Helper()
	switch c.Fn {
	case "fftfreq":
		return FFTFreq(*c.N, 0.1)
	case "rfftfreq":
		return RFFTFreq(*c.N, 0.1)
	}
	dt, err := ndarray.ParseDType(c.DType)
	if err != nil {
		t.Fatal(err)
	}
	vals := parseValues(t, c.X)
	x, _ := ndarray.FromSlice(vals, c.Shape...)
	x = x.AsType(dt)
	switch c.Fn {
	case "fftshift":
		return FFTShift(x, c.Axes...)
	case "ifftshift":
		return IFFTShift(x, c.Axes...)
	}
	o := Options{S: c.S, Axes: c.Axes}
	if c.N != nil {
		o.S = []int{*c.N}
	}
	if c.Axis != nil {
		o.Axes = []int{*c.Axis}
	}
	if c.Norm != nil {
		o.Norm = norms[*c.Norm]
	}
	return transforms[c.Fn](x, o)
}

func TestDefaultsEqualWith(t *testing.T) {
	x, _ := ndarray.FromSlice([]float64{1, 2, 3, 4, 5, 6}, 2, 3)
	pairs := []struct {
		name string
		f    func(*ndarray.Array) (*ndarray.Array, error)
		g    transform
	}{
		{"FFT", FFT, FFTWith}, {"IFFT", IFFT, IFFTWith}, {"RFFT", RFFT, RFFTWith}, {"IRFFT", IRFFT, IRFFTWith},
		{"HFFT", HFFT, HFFTWith}, {"IHFFT", IHFFT, IHFFTWith}, {"FFT2", FFT2, FFT2With}, {"IFFT2", IFFT2, IFFT2With},
		{"RFFT2", RFFT2, RFFT2With}, {"IRFFT2", IRFFT2, IRFFT2With}, {"FFTN", FFTN, FFTNWith},
		{"IFFTN", IFFTN, IFFTNWith}, {"RFFTN", RFFTN, RFFTNWith}, {"IRFFTN", IRFFTN, IRFFTNWith},
	}
	for _, p := range pairs {
		a, err1 := p.f(x)
		b, err2 := p.g(x, Options{})
		if err1 != nil || err2 != nil || a.String() != b.String() {
			t.Errorf("%s differs from its With form: %v %v", p.name, err1, err2)
		}
	}
}

func TestArgumentErrors(t *testing.T) {
	x, _ := ndarray.Zeros(4, 4)
	for name, o := range map[string]Options{
		"two axes for 1-D": {Axes: []int{0, 1}},
		"S/axes length":    {S: []int{2, 2}, Axes: []int{0}},
	} {
		if _, err := FFTWith(x, o); !errors.Is(err, ErrArgs) {
			t.Errorf("%s: err = %v", name, err)
		}
	}
	if _, err := FFTNWith(x, Options{Axes: []int{}}); !errors.Is(err, ErrArgs) {
		t.Errorf("no axes: err = %v", err)
	}
	// A repeated axis is transformed twice, in numpy's order, with the lengths
	// numpy fixes before the first pass (so the 3 bins are padded back to 4).
	y, _ := ndarray.FromSlice([]float64{1, 2, 3, 4, 5, 6, 7, 8}, 2, 4)
	r, err := RFFTNWith(y, Options{Axes: []int{1, 1}})
	step, _ := RFFTWith(y, Options{Axes: []int{1}})
	step, _ = FFTWith(step, Options{Axes: []int{1}, S: []int{4}})
	if err != nil || r.String() != step.String() {
		t.Errorf("rfftn over a repeated axis = %v, %v; want %v", r, err, step)
	}
	r, err = IRFFTNWith(step, Options{Axes: []int{1, 1}, S: []int{3, 4}})
	inv, _ := IFFTWith(step, Options{Axes: []int{1}, S: []int{3}})
	inv, _ = IRFFTWith(inv, Options{Axes: []int{1}, S: []int{4}})
	if err != nil || r.String() != inv.String() {
		t.Errorf("irfftn over a repeated axis = %v, %v; want %v", r, err, inv)
	}
	if _, err := RFFTNWith(y, Options{Axes: []int{1, 1}, S: []int{4, 0}}); !errors.Is(err, ErrArgs) {
		t.Errorf("repeated axis with a zero length: err = %v", err)
	}
	if _, err := FFTNWith(x, Options{S: []int{4}}); err != nil {
		t.Errorf("S selects the last axis: %v", err)
	}
	for _, n := range []int{0, -1} {
		if _, err := FFTFreq(n, 1); !errors.Is(err, ErrArgs) {
			t.Errorf("FFTFreq(%d) err = %v", n, err)
		}
		if _, err := RFFTFreq(n, 1); !errors.Is(err, ErrArgs) {
			t.Errorf("RFFTFreq(%d) err = %v", n, err)
		}
	}
	if _, err := FFTShift(x, 2); !errors.Is(err, ErrArgs) {
		t.Errorf("FFTShift axis err = %v", err)
	}
	s, _ := ndarray.FromSlice([]int8{3}, []int{}...)
	if r, err := FFTShift(s); err != nil || r == s || r.String() != s.String() {
		t.Errorf("FFTShift of a 0-d array = %v, %v", r, err)
	}
	if r, _ := FFTShift(x, []int{}...); r == x {
		t.Error("FFTShift returned its input")
	}
}

// TestNormsAreInverse checks the round trip under each scaling, in both
// precisions.
func TestNormsAreInverse(t *testing.T) {
	for _, dt := range []ndarray.DType{ndarray.Float64, ndarray.Float32} {
		x, _ := ndarray.FromSlice([]float64{1, -2, 3, 0.5, 4, -1}, 6)
		x = x.AsType(dt)
		for _, n := range []Norm{Backward, Ortho, Forward} {
			f, _ := RFFTWith(x, Options{Norm: n})
			b, _ := IRFFTWith(f, Options{S: []int{6}, Norm: n})
			if b.DType() != dt {
				t.Fatalf("%v round trip gives %v", dt, b.DType())
			}
			for i := range 6 {
				if math.Abs(b.At(i)-x.At(i)) > 1e-5 {
					t.Errorf("%v %v: [%d] %g != %g", dt, n, i, b.At(i), x.At(i))
				}
			}
		}
	}
}
