package kernels

// arm64 GEMM micro-kernel: a NEON 4x8 register-blocked tile (gemm in
// sum_arm64.s, generated by go-asmgen). See asmgen/arm64/gen.go for the register
// map. It uses the WORD-encoded by-element double FMLA (FMLA Vd.2D, Vn.2D,
// Vm.D[i] — the one instruction Go's arm64 assembler cannot name), so each A
// scalar folds straight from a loaded vector lane, eliminating the MOVD-to-GP +
// VDUP round-trip the prior 4x8 kernel paid per A value every k-step. The 4-row x
// 8-col tile (16 D2 accumulators) fits in one pass with B in 4 vectors and the A
// column in 2, and 4|N, 8|N aligns with the power-of-two sizes so there is no
// scalar edge. MR x NR = 4 x 8 is the tile the packing produces.

// MR, NR are the micro-kernel's register-block dimensions: it computes an
// MR-row x NR-col tile of C per call. The packing in gemm.go produces MR-tall A
// panels and NR-wide B panels to match.
const (
	MR = 4
	NR = 8
)

// gemmMicro adds the MR x NR tile sum_p pa[p*MR..]*pb[p*NR..] into the C block at
// dst[0:], whose rows are ldc apart, using the NEON kernel. pa, pb hold at least
// kc*MR and kc*NR packed (zero-padded) doubles; dst has at least (MR-1)*ldc + NR
// elements. Bit-identical to the scalar ikj accumulation (see gemmEdge).
func gemmMicro(kc int, pa, pb, dst []float64, ldc int) {
	gemmMicro4x8(kc, &pa[0], &pb[0], &dst[0], ldc)
}

//go:noescape
func gemmMicro4x8(kc int, pa, pb, c *float64, ldc int)
