package kernels

// riscv64 GEMM micro-kernel: a 6x8 RVV tile (gemmMicro6x8RVV in
// sum_riscv64.s, generated by go-asmgen): six accumulator groups of eight
// float64 (LMUL=4, eight lanes on any VLEN >= 128), the B row loaded once per
// step and each A value fused in with vfmacc.vf. Without V, gemmMicroGo
// computes the same tile in scalar code.

// MR, NR are the micro-kernel's register-block dimensions.
const (
	MR = 6
	NR = 8
)

func gemmMicro(kc int, pa, pb, dst []float64, ldc int) {
	if useRVV {
		_, _, _ = pa[kc*MR-1], pb[kc*NR-1], dst[(MR-1)*ldc+NR-1] // the kernel's whole reach
		gemmMicro6x8RVV(kc, &pa[0], &pb[0], &dst[0], ldc)
		return
	}
	gemmMicroGo(kc, pa, pb, dst, ldc)
}

// gemmMicroGo is the scalar MR x NR tile: dst[r*ldc+c] += sum_p
// pa[p*MR+r]*pb[p*NR+c], in p order per element.
func gemmMicroGo(kc int, pa, pb, dst []float64, ldc int) {
	var acc [MR * NR]float64
	for p := 0; p < kc; p++ {
		a := pa[p*MR : p*MR+MR : p*MR+MR]
		b := pb[p*NR : p*NR+NR : p*NR+NR]
		for r, av := range a {
			row := acc[r*NR : r*NR+NR : r*NR+NR]
			for c, bv := range b {
				row[c] += av * bv
			}
		}
	}
	for r := 0; r < MR; r++ {
		d := dst[r*ldc : r*ldc+NR : r*ldc+NR]
		for c := range d {
			d[c] += acc[r*NR+c]
		}
	}
}

//go:noescape
func gemmMicro6x8RVV(kc int, pa, pb, c *float64, ldc int)
