package kernels

// loong64 GEMM micro-kernel: an 8x8 LASX tile (gemmMicro8x8LASX in
// sum_loong64.s, generated by go-asmgen): 16 four-lane accumulators, the B row
// in two vectors, each A value broadcast by xvldrepl.d (XVMOVQ .V4) and a
// fused xvfmadd.d.
// Without LASX, gemmMicroGo computes the same tile in scalar code.

// MR, NR are the micro-kernel's register-block dimensions.
const (
	MR = 8
	NR = 8
)

func gemmMicro(kc int, pa, pb, dst []float64, ldc int) {
	if useLASX {
		_, _, _ = pa[kc*MR-1], pb[kc*NR-1], dst[(MR-1)*ldc+NR-1] // the kernel's whole reach
		gemmMicro8x8LASX(kc, &pa[0], &pb[0], &dst[0], ldc)
		return
	}
	gemmMicroGo(kc, pa, pb, dst, ldc)
}

// gemmMicroGo is the scalar MR x NR tile: dst[r*ldc+c] += sum_p
// pa[p*MR+r]*pb[p*NR+c], in p order per element.
func gemmMicroGo(kc int, pa, pb, dst []float64, ldc int) {
	var acc [MR * NR]float64
	for p := 0; p < kc; p++ {
		a := pa[p*MR : p*MR+MR : p*MR+MR]
		b := pb[p*NR : p*NR+NR : p*NR+NR]
		for r, av := range a {
			row := acc[r*NR : r*NR+NR : r*NR+NR]
			for c, bv := range b {
				row[c] += av * bv
			}
		}
	}
	for r := 0; r < MR; r++ {
		d := dst[r*ldc : r*ldc+NR : r*ldc+NR]
		for c := range d {
			d[c] += acc[r*NR+c]
		}
	}
}

// dotSIMD is the inner product (LASX kernel, four fused accumulators).
func dotSIMD(a, b []float64) float64 {
	if !useLASX || len(a) == 0 {
		return dotRange(a, b)
	}
	_ = b[len(a)-1] // the kernel reads len(a) of b
	return dotLASX(&a[0], &b[0], len(a))
}

//go:noescape
func gemmMicro8x8LASX(kc int, pa, pb, c *float64, ldc int)

//go:noescape
func dotLASX(a, b *float64, n int) float64
