package kernels

// amd64 GEMM micro-kernel: a 6x8 register-blocked tile (gemm in sum_amd64.s,
// generated by go-asmgen), the BLIS Haswell dgemm shape. Two kernels share the
// one 6x8 packing:
//
//   - gemmMicro6x8FMA, AVX2-era FMA3: 12 YMM accumulators, VBROADCASTSD of each
//     A value and VFMADD231PD against the two-YMM B row. Taken when hasFMA
//     (CPUID FMA, AVX and OSXSAVE, and XCR0 saving YMM state) says so — every
//     Intel and AMD part since 2013.
//   - gemmMicro6x4SSE2, the GOAMD64=v1 baseline, called twice per tile (columns
//     0-3, then 4-7): explicit MULPD+ADDPD, since SSE2 has no FMA.
//
// The FMA kernel rounds each a*b+c once, as tuned BLAS and arm64's kernel do; the
// SSE2 one rounds twice, as the scalar oracle does at GOAMD64=v1. On data whose
// products and partial sums are exact (the integer-valued tests) the two agree
// bit-for-bit with the oracle; elsewhere they can differ in the last place.

// MR, NR are the micro-kernel's register-block dimensions: it computes an
// MR-row x NR-col tile of C per call. The packing in gemm.go matches.
const (
	MR = 6
	NR = 8
)

// gemmUseFMA selects the FMA kernel. It is a var so tests can force the SSE2
// path on hardware that has FMA (never the reverse: that would fault).
var gemmUseFMA = hasFMA()

// gemmMicro adds the MR x NR tile sum_p pa[p*MR..]*pb[p*NR..] into the C block at
// dst[0:], whose rows are ldc apart. pa, pb hold at least kc*MR and kc*NR packed
// (zero-padded) doubles; dst has at least (MR-1)*ldc + NR elements.
func gemmMicro(kc int, pa, pb, dst []float64, ldc int) {
	if gemmUseFMA {
		gemmMicro6x8FMA(kc, &pa[0], &pb[0], &dst[0], ldc)
		return
	}
	gemmMicro6x4SSE2(kc, &pa[0], &pb[0], &dst[0], ldc)
	gemmMicro6x4SSE2(kc, &pa[0], &pb[4], &dst[4], ldc)
}

//go:noescape
func gemmMicro6x8FMA(kc int, pa, pb, c *float64, ldc int)

//go:noescape
func gemmMicro6x4SSE2(kc int, pa, pb, c *float64, ldc int)

// hasFMA reports CPU and OS support for the FMA kernel (go-asmgen FeatureProbe).
func hasFMA() bool
