package kernels

// amd64 GEMM micro-kernel: an SSE2 4x4 register-blocked tile (gemm in
// sum_amd64.s, generated by go-asmgen). amd64 baseline is SSE2 (GOAMD64=v1) with
// no FMA, so the kernel uses explicit MULPD+ADDPD; SSE2's packed FP add keeps the
// accumulation in the same ikj order as the scalar oracle (bit-identical).
// MR x NR = 4 x 4 fits the 16 XMM registers (8 for the C tile).

// MR, NR are the micro-kernel's register-block dimensions: it computes an
// MR-row x NR-col tile of C per call. The packing in gemm.go matches.
const (
	MR = 4
	NR = 4
)

// gemmMicro adds the MR x NR tile sum_p pa[p*MR..]*pb[p*NR..] into the C block at
// dst[0:], whose rows are ldc apart, using the SSE2 kernel. pa, pb hold at least
// kc*MR and kc*NR packed (zero-padded) doubles; dst has at least (MR-1)*ldc + NR
// elements. Bit-identical to the scalar ikj accumulation (see gemmEdge).
func gemmMicro(kc int, pa, pb, dst []float64, ldc int) {
	gemmMicro4x4(kc, &pa[0], &pb[0], &dst[0], ldc)
}

//go:noescape
func gemmMicro4x4(kc int, pa, pb, c *float64, ldc int)
