package kernels

// s390x GEMM micro-kernel: a 4x8 vector-facility tile (gemmMicro4x8VX in
// sum_s390x.s, generated by go-asmgen): sixteen two-lane accumulators, the B
// row loaded once per step with VLM, each A value replicated with VLREPG and
// fused in with VFMADB. Without the facility, gemmMicroGo computes the same
// tile in scalar code.

// MR, NR are the micro-kernel's register-block dimensions.
const (
	MR = 4
	NR = 8
)

func gemmMicro(kc int, pa, pb, dst []float64, ldc int) {
	if useVX {
		_, _, _ = pa[kc*MR-1], pb[kc*NR-1], dst[(MR-1)*ldc+NR-1] // the kernel's whole reach
		gemmMicro4x8VX(kc, &pa[0], &pb[0], &dst[0], ldc)
		return
	}
	gemmMicroGo(kc, pa, pb, dst, ldc)
}

// gemmMicroGo is the scalar MR x NR tile: dst[r*ldc+c] += sum_p
// pa[p*MR+r]*pb[p*NR+c], in p order per element.
func gemmMicroGo(kc int, pa, pb, dst []float64, ldc int) {
	var acc [MR * NR]float64
	for p := 0; p < kc; p++ {
		a := pa[p*MR : p*MR+MR : p*MR+MR]
		b := pb[p*NR : p*NR+NR : p*NR+NR]
		for r, av := range a {
			row := acc[r*NR : r*NR+NR : r*NR+NR]
			for c, bv := range b {
				row[c] += av * bv
			}
		}
	}
	for r := 0; r < MR; r++ {
		d := dst[r*ldc : r*ldc+NR : r*ldc+NR]
		for c := range d {
			d[c] += acc[r*NR+c]
		}
	}
}

//go:noescape
func gemmMicro4x8VX(kc int, pa, pb, c *float64, ldc int)
