package kernels

// ppc64le GEMM micro-kernel: an 8x8 VSX tile (gemmMicro8x8VSX in
// sum_ppc64le.s, generated by go-asmgen): 32 two-lane accumulators, the B row
// loaded with LXVD2X, each A value splatted with LXVDSX, and a fused
// XVMADDADP per (row, column pair). Fused like the arm64 and amd64 FMA
// kernels: on integer-valued data it equals the scalar ikj oracle exactly.

// MR, NR are the micro-kernel's register-block dimensions: it computes an
// MR-row x NR-col tile of C per call. The packing in gemm.go matches.
const (
	MR = 8
	NR = 8
)

// gemmMicro adds the MR x NR tile sum_p pa[p*MR..]*pb[p*NR..] into the C block
// at dst[0:], whose rows are ldc apart.
func gemmMicro(kc int, pa, pb, dst []float64, ldc int) {
	gemmMicro8x8VSX(kc, &pa[0], &pb[0], &dst[0], ldc)
}

// dotSIMD is the inner product of two equal-length slices (VSX kernel, four
// fused multiply-add accumulators).
func dotSIMD(a, b []float64) float64 {
	if len(a) == 0 {
		return 0
	}
	return dotVSX(&a[0], &b[0], len(a))
}

//go:noescape
func gemmMicro8x8VSX(kc int, pa, pb, c *float64, ldc int)

//go:noescape
func dotVSX(a, b *float64, n int) float64
