package kernels

// amd64: an SSE2 float64 sum-reduction kernel generated by go-asmgen
// (sum_amd64.s). SSE2 is part of the amd64 baseline (GOAMD64=v1), so sumSIMD is
// always callable — there is no CPU-feature branch.
//
//go:generate sh -c "cd asmgen/amd64 && GOFLAGS=-mod=mod go run gen.go && mv sum_amd64.s ../../sum_amd64.s"

// HaveReduceSIMD reports that this build ships a SIMD reduction kernel.
const HaveReduceSIMD = true

// sumSIMD returns the SIMD sum of a (empty -> 0), using four SSE2 accumulators.
// The lane-parallel grouping can differ from sequential Sum by a few ULP.
func sumSIMD(a []float64) float64 {
	if len(a) == 0 {
		return 0
	}
	return sumSSE2(&a[0], len(a))
}

//go:noescape
func sumSSE2(a *float64, n int) float64
