package kernels

// arm64 kernels. The sum reduction is a hand-vectorized NEON kernel generated by
// go-asmgen (sum_arm64.s, using VFMLA against a vector of 1.0 — see asmgen).
//
//go:generate sh -c "cd asmgen/arm64 && GOFLAGS=-mod=mod go run gen.go && mv sum_arm64.s ../../sum_arm64.s"
//
// sqrt/max/min are NOT hand-vectorized on arm64: Go's arm64 assembler exposes
// no packed vector-double sqrt/max/min (only VFMLA/VFMLS), but it DOES intrinsify
// the *scalar* math.Sqrt -> FSQRTD and math.Max/math.Min -> FMAXD/FMIND. So the
// direct scalar oracle loops already compile to the hardware instructions with no
// per-element call overhead — the win over the old func-pointer Map path (which
// could not intrinsify math.Sqrt and paid a real call per element, ~2.7x slower)
// plus the multicore fan-out is what beats numpy. arm64's FMAXD/FMIND propagate
// NaN, matching the math.Max-based oracle and numpy.

// HaveReduceSIMD reports that this build ships at least one hand-vectorized SIMD
// kernel (the NEON sum). The per-arch CI execution job validates it against the
// scalar oracle to a tight relative tolerance.
const HaveReduceSIMD = true

// sumSIMD returns the SIMD sum of a (empty -> 0), using four NEON accumulators.
// The lane-parallel grouping can differ from sequential Sum by a few ULP.
func sumSIMD(a []float64) float64 {
	if len(a) == 0 {
		return 0
	}
	return sumNEON(&a[0], len(a))
}

// sqrtSIMD writes sqrt(src[i]) into dst[i]. On arm64 this is the direct scalar
// oracle, which the compiler lowers to the FSQRTD hardware instruction per
// element (bit-identical to math.Sqrt). It is exported through the same seam so
// callers and the parallel wrapper are architecture-independent.
func sqrtSIMD(dst, src []float64) { sqrtScalar(dst, src) }

// maxSIMD / minSIMD are the four-accumulator NaN-propagating reducers: the
// builtin max/min lower to the FMAXD/FMIND hardware instructions and the four
// independent chains hide their latency (~3.6x over one accumulator). They are
// bit-identical to the serial Max/Min oracle (max/min is associative for the
// NaN-propagating rule). A packed vector max is not expressible on arm64 (Go's
// assembler exposes no VFMAX.D2, only VFMLA/VFMLS), so this register-unrolled
// scalar form is the arm64 SIMD path.
func maxSIMD(a []float64) float64 { return maxUnrolled(a) }
func minSIMD(a []float64) float64 { return minUnrolled(a) }

//go:noescape
func sumNEON(a *float64, n int) float64
