package kernels

// ppc64le VSX kernels generated by go-asmgen (sum_ppc64le.s). VSX is part of
// the ppc64le baseline (POWER8, GOPPC64=power8), so they are always callable.
// Go's ppc64 assembler has no vector double arithmetic; go-asmgen encodes it
// (xvadddp, xvmaddadp, ...) as WORDs, checked against GNU as.
//
//go:generate sh -c "cd asmgen/ppc64le && go run . && mv sum_ppc64le.s ../../sum_ppc64le.s"

// HaveReduceSIMD reports that this build ships SIMD reduction/elementwise
// kernels.
const HaveReduceSIMD = true

// sumSIMD returns the VSX sum of a (empty -> 0): four accumulators, a valid
// regrouping of the sum, like the other targets' SIMD sums.
func sumSIMD(a []float64) float64 {
	if len(a) == 0 {
		return 0
	}
	return sumVSX(&a[0], len(a))
}

// sqrtSIMD writes sqrt(src[i]) into dst[i] with XVSQRTDP, bit-identical to
// math.Sqrt (one correctly rounded operation per lane).
func sqrtSIMD(dst, src []float64) {
	if len(dst) == 0 {
		return
	}
	_ = src[len(dst)-1] // the kernel reads len(dst) of src
	sqrtVSX(&dst[0], &src[0], len(dst))
}

// max/min stay on the four-accumulator scalar reducers: XVMAXDP/XVMINDP do not
// propagate NaN the way Go's max/min and numpy.max do.
func maxSIMD(a []float64) float64 { return maxUnrolled(a) }
func minSIMD(a []float64) float64 { return minUnrolled(a) }

// addBin, subBin, mulBin, divBin write dst[i] = a[i] OP b[i] with the VSX
// kernels, each lane one IEEE operation, bit-identical to the scalar oracle.
func addBin(dst, a, b []float64) {
	if len(dst) > 0 {
		_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
		addVSX(&dst[0], &a[0], &b[0], len(dst))
	}
}

func subBin(dst, a, b []float64) {
	if len(dst) > 0 {
		_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
		subVSX(&dst[0], &a[0], &b[0], len(dst))
	}
}

func mulBin(dst, a, b []float64) {
	if len(dst) > 0 {
		_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
		mulVSX(&dst[0], &a[0], &b[0], len(dst))
	}
}

func divBin(dst, a, b []float64) {
	if len(dst) > 0 {
		_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
		divVSX(&dst[0], &a[0], &b[0], len(dst))
	}
}

//go:noescape
func sumVSX(a *float64, n int) float64

//go:noescape
func sqrtVSX(dst, src *float64, n int)

//go:noescape
func addVSX(dst, a, b *float64, n int)

//go:noescape
func subVSX(dst, a, b *float64, n int)

//go:noescape
func mulVSX(dst, a, b *float64, n int)

//go:noescape
func divVSX(dst, a, b *float64, n int)
