package kernels

import "os"

// s390x vector-facility kernels generated by go-asmgen (sum_s390x.s): two
// float64 per register, eight per loop, a scalar tail. Every s390x Go runs on
// (z13 and later) has the facility, but a kernel can still disable it, so each
// wrapper uses the kernel only when AT_HWCAP reports it, and runs the scalar
// oracle otherwise.
//
//go:generate sh -c "cd asmgen/s390x && go run . && mv sum_s390x.s ../../sum_s390x.s"
//
// max/min use the vector max with NumPy's NaN rule (VFMAXDB, Java mode) on
// a z14 or later (vector-enhancements facility 1, AT_HWCAP VXRS_EXT), and the
// scalar reducers on the z13 that Go also supports.

// HaveReduceSIMD reports that this build ships SIMD kernels; they run when
// useVX is true.
const HaveReduceSIMD = true

// hwcapVX is HWCAP_S390_VXRS (Linux arch/s390/include/asm/elf.h: bit 11).
const hwcapVX = 1 << 11

// useVX selects the vector kernels. A var so tests can force the scalar path
// on hardware that has the facility (never the reverse: that would fault).
var useVX = vxFromAuxv()

func vxFromAuxv() bool {
	auxv, err := os.ReadFile("/proc/self/auxv")
	return err == nil && hwcapFrom(auxv)&hwcapVX != 0
}

func sumSIMD(a []float64) float64 {
	if !useVX || len(a) == 0 {
		return Sum(a)
	}
	return sumVX(&a[0], len(a))
}

func sqrtSIMD(dst, src []float64) {
	if !useVX || len(dst) == 0 {
		sqrtScalar(dst, src)
		return
	}
	_ = src[len(dst)-1] // the kernel reads len(dst) of src
	sqrtVX(&dst[0], &src[0], len(dst))
}

// hwcapVXE is HWCAP_S390_VXRS_EXT (bit 13), the vector-enhancements facility 1
// of the z14, which brings VFMAXDB/VFMINDB.
const hwcapVXE = 1 << 13

// useVXE selects the vector max/min. A var so tests can force the scalar path.
var useVXE = vxeFromAuxv()

func vxeFromAuxv() bool {
	auxv, err := os.ReadFile("/proc/self/auxv")
	return err == nil && hwcapFrom(auxv)&hwcapVXE != 0
}

// maxSIMD / minSIMD are the NaN-propagating extrema of a (non-empty): the
// VFMAXDB/VFMINDB kernel in Java mode from eight elements up on a z14 or
// later, the four-chain scalar reducer otherwise.
func maxSIMD(a []float64) float64 {
	if !useVXE || len(a) < 8 {
		return maxUnrolled(a)
	}
	return maxVXE(&a[0], len(a))
}

func minSIMD(a []float64) float64 {
	if !useVXE || len(a) < 8 {
		return minUnrolled(a)
	}
	return minVXE(&a[0], len(a))
}

func addBin(dst, a, b []float64) {
	if !useVX || len(dst) == 0 {
		Add(dst, a, b)
		return
	}
	_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
	addVX(&dst[0], &a[0], &b[0], len(dst))
}

func subBin(dst, a, b []float64) {
	if !useVX || len(dst) == 0 {
		Sub(dst, a, b)
		return
	}
	_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
	subVX(&dst[0], &a[0], &b[0], len(dst))
}

func mulBin(dst, a, b []float64) {
	if !useVX || len(dst) == 0 {
		Mul(dst, a, b)
		return
	}
	_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
	mulVX(&dst[0], &a[0], &b[0], len(dst))
}

func divBin(dst, a, b []float64) {
	if !useVX || len(dst) == 0 {
		Div(dst, a, b)
		return
	}
	_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
	divVX(&dst[0], &a[0], &b[0], len(dst))
}

// dotSIMD is the inner product (vector kernel, four fused two-lane accumulators).
func dotSIMD(a, b []float64) float64 {
	if !useVX || len(a) == 0 {
		return dotRange(a, b)
	}
	_ = b[len(a)-1] // the kernel reads len(a) of b
	return dotVX(&a[0], &b[0], len(a))
}

//go:noescape
func sumVX(a *float64, n int) float64

//go:noescape
func dotVX(a, b *float64, n int) float64

//go:noescape
func sqrtVX(dst, src *float64, n int)

//go:noescape
func addVX(dst, a, b *float64, n int)

//go:noescape
func subVX(dst, a, b *float64, n int)

//go:noescape
func mulVX(dst, a, b *float64, n int)

//go:noescape
func divVX(dst, a, b *float64, n int)

//go:noescape
func maxVXE(a *float64, n int) float64

//go:noescape
func minVXE(a *float64, n int) float64
