package kernels

import "os"

// riscv64 RVV kernels generated by go-asmgen (sum_riscv64.s). The vector
// extension is optional on RISC-V, so each wrapper uses the kernel only when
// the kernel reports V in AT_HWCAP, and runs the scalar oracle otherwise. The
// loops are vector-length agnostic: they run on any VLEN.
//
//go:generate sh -c "cd asmgen/riscv64 && go run . && mv sum_riscv64.s ../../sum_riscv64.s"
//
// max/min stay on the scalar reducers: RVV's vfmax/vfmin follow IEEE 754-2019
// maximumNumber, which returns the number when the other operand is a NaN,
// where NumPy and Go's max propagate the NaN.

// HaveReduceSIMD reports that this build ships SIMD kernels; they run when
// useRVV is true.
const HaveReduceSIMD = true

// hwcapV is COMPAT_HWCAP_ISA_V, the bit of 'V' in the letter-indexed riscv
// AT_HWCAP (Linux arch/riscv/include/asm/hwcap.h: 1 << ('V' - 'A')). The kernel
// sets it only when it also saves vector state across context switches.
const hwcapV = 1 << ('V' - 'A')

// useRVV selects the RVV kernels. A var so tests can force the scalar path on
// hardware that has V (never the reverse: that would fault).
var useRVV = rvvFromAuxv()

func rvvFromAuxv() bool {
	auxv, err := os.ReadFile("/proc/self/auxv")
	return err == nil && hwcapFrom(auxv)&hwcapV != 0
}

func sumSIMD(a []float64) float64 {
	if !useRVV || len(a) == 0 {
		return Sum(a)
	}
	return sumRVV(&a[0], len(a))
}

func sqrtSIMD(dst, src []float64) {
	if !useRVV || len(dst) == 0 {
		sqrtScalar(dst, src)
		return
	}
	_ = src[len(dst)-1] // the kernel reads len(dst) of src
	sqrtRVV(&dst[0], &src[0], len(dst))
}

func maxSIMD(a []float64) float64 { return maxUnrolled(a) }
func minSIMD(a []float64) float64 { return minUnrolled(a) }

func addBin(dst, a, b []float64) {
	if !useRVV || len(dst) == 0 {
		Add(dst, a, b)
		return
	}
	_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
	addRVV(&dst[0], &a[0], &b[0], len(dst))
}

func subBin(dst, a, b []float64) {
	if !useRVV || len(dst) == 0 {
		Sub(dst, a, b)
		return
	}
	_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
	subRVV(&dst[0], &a[0], &b[0], len(dst))
}

func mulBin(dst, a, b []float64) {
	if !useRVV || len(dst) == 0 {
		Mul(dst, a, b)
		return
	}
	_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
	mulRVV(&dst[0], &a[0], &b[0], len(dst))
}

func divBin(dst, a, b []float64) {
	if !useRVV || len(dst) == 0 {
		Div(dst, a, b)
		return
	}
	_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
	divRVV(&dst[0], &a[0], &b[0], len(dst))
}

// dotSIMD is the inner product (RVV kernel, one fused accumulator per lane).
func dotSIMD(a, b []float64) float64 {
	if !useRVV || len(a) == 0 {
		return dotRange(a, b)
	}
	_ = b[len(a)-1] // the kernel reads len(a) of b
	return dotRVV(&a[0], &b[0], len(a))
}

//go:noescape
func sumRVV(a *float64, n int) float64

//go:noescape
func dotRVV(a, b *float64, n int) float64

//go:noescape
func sqrtRVV(dst, src *float64, n int)

//go:noescape
func addRVV(dst, a, b *float64, n int)

//go:noescape
func subRVV(dst, a, b *float64, n int)

//go:noescape
func mulRVV(dst, a, b *float64, n int)

//go:noescape
func divRVV(dst, a, b *float64, n int)
