package kernels

// amd64 SSE2 kernels generated by go-asmgen (sum_amd64.s). SSE2 is part of the
// amd64 baseline (GOAMD64=v1), so every kernel here is always callable — there
// is no CPU-feature branch.
//
//go:generate sh -c "cd asmgen/amd64 && GOFLAGS=-mod=mod go run gen.go && mv sum_amd64.s ../../sum_amd64.s"

// HaveReduceSIMD reports that this build ships SIMD reduction/elementwise
// kernels (so the dispatch wrappers route through them rather than the scalar
// oracle). True on amd64/arm64; false on the four arches without vector double.
const HaveReduceSIMD = true

// sumSIMD returns the SIMD sum of a (empty -> 0), using four SSE2 accumulators.
// The lane-parallel grouping can differ from sequential Sum by a few ULP.
func sumSIMD(a []float64) float64 {
	if len(a) == 0 {
		return 0
	}
	return sumSSE2(&a[0], len(a))
}

// sqrtSIMD writes sqrt(src[i]) into dst[i] with the packed SSE2 SQRTPD kernel.
// SQRTPD computes the same correctly-rounded IEEE square root the scalar oracle
// (math.Sqrt) does, lane-by-lane, so it is bit-identical to sqrtScalar including
// NaN/Inf/signed-zero. len(dst) == len(src) is guaranteed by the caller.
func sqrtSIMD(dst, src []float64) {
	if len(dst) == 0 {
		return
	}
	sqrtSSE2(&dst[0], &src[0], len(dst))
}

// maxSIMD returns the NaN-propagating maximum of a (non-empty): if any element
// is NaN the result is NaN, otherwise the largest element — matching the
// math.Max-based scalar oracle (Max) and numpy.max bit-for-bit. The SSE2 kernel
// accumulates a packed running max with MAXPD and a separate "saw NaN" mask via
// CMPUNORDPD, then returns NaN if any lane ever held a NaN.
func maxSIMD(a []float64) float64 {
	return maxSSE2(&a[0], len(a))
}

// minSIMD returns the NaN-propagating minimum of a (non-empty), the dual of
// maxSIMD via MINPD; bit-identical to the scalar Min oracle and numpy.min.
func minSIMD(a []float64) float64 {
	return minSSE2(&a[0], len(a))
}

//go:noescape
func sumSSE2(a *float64, n int) float64

//go:noescape
func sqrtSSE2(dst, src *float64, n int)

//go:noescape
func maxSSE2(a *float64, n int) float64

//go:noescape
func minSSE2(a *float64, n int) float64
