package kernels

import "os"

// loong64 LASX kernels generated by go-asmgen (sum_loong64.s). LASX (256-bit,
// four float64 lanes) is not on every LoongArch CPU, so each wrapper uses it
// only when the kernel reports it in AT_HWCAP, and runs the scalar oracle
// otherwise.
//
//go:generate sh -c "cd asmgen/loong64 && go run . && mv sum_loong64.s ../../sum_loong64.s"

// HaveReduceSIMD reports that this build ships SIMD kernels; they run when
// useLASX is true.
const HaveReduceSIMD = true

// hwcapLASX is HWCAP_LOONGARCH_LASX (Linux arch/loongarch/include/uapi/asm/hwcap.h).
const hwcapLASX = 1 << 5

// useLASX selects the LASX kernels. A var so tests can force the scalar path
// on hardware that has LASX (never the reverse: that would fault).
var useLASX = lasxFromAuxv()

func lasxFromAuxv() bool {
	auxv, err := os.ReadFile("/proc/self/auxv")
	return err == nil && hwcapFrom(auxv)&hwcapLASX != 0
}

func sumSIMD(a []float64) float64 {
	if !useLASX || len(a) == 0 {
		return Sum(a)
	}
	return sumLASX(&a[0], len(a))
}

func sqrtSIMD(dst, src []float64) {
	if !useLASX || len(dst) == 0 {
		sqrtScalar(dst, src)
		return
	}
	_ = src[len(dst)-1] // the kernel reads len(dst) of src
	sqrtLASX(&dst[0], &src[0], len(dst))
}

// max/min stay on the four-accumulator scalar reducers.
func maxSIMD(a []float64) float64 { return maxUnrolled(a) }
func minSIMD(a []float64) float64 { return minUnrolled(a) }

func addBin(dst, a, b []float64) {
	if !useLASX || len(dst) == 0 {
		Add(dst, a, b)
		return
	}
	_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
	addLASX(&dst[0], &a[0], &b[0], len(dst))
}

func subBin(dst, a, b []float64) {
	if !useLASX || len(dst) == 0 {
		Sub(dst, a, b)
		return
	}
	_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
	subLASX(&dst[0], &a[0], &b[0], len(dst))
}

func mulBin(dst, a, b []float64) {
	if !useLASX || len(dst) == 0 {
		Mul(dst, a, b)
		return
	}
	_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
	mulLASX(&dst[0], &a[0], &b[0], len(dst))
}

func divBin(dst, a, b []float64) {
	if !useLASX || len(dst) == 0 {
		Div(dst, a, b)
		return
	}
	_, _ = a[len(dst)-1], b[len(dst)-1] // the kernel reads len(dst) of each
	divLASX(&dst[0], &a[0], &b[0], len(dst))
}

//go:noescape
func sumLASX(a *float64, n int) float64

//go:noescape
func sqrtLASX(dst, src *float64, n int)

//go:noescape
func addLASX(dst, a, b *float64, n int)

//go:noescape
func subLASX(dst, a, b *float64, n int)

//go:noescape
func mulLASX(dst, a, b *float64, n int)

//go:noescape
func divLASX(dst, a, b *float64, n int)
