package kernels

// arm64: NEON float64 reduction kernels generated by go-asmgen (sum_arm64.s).
// NEON (ASIMD) is part of the arm64 baseline the Go toolchain requires, so the
// SIMD reductions are always callable — there is no CPU-feature branch.
//
//go:generate sh -c "cd asmgen/arm64 && GOFLAGS=-mod=mod go run gen.go && mv sum_arm64.s ../../sum_arm64.s"

// HaveReduceSIMD reports that this build ships a SIMD reduction kernel, so the
// dispatch wrappers route Sum through it. The per-arch CI execution job
// validates it against the scalar oracle to a tight relative tolerance (the
// lane-parallel grouping is a different-but-valid summation order, like numpy).
const HaveReduceSIMD = true

// sumSIMD returns the SIMD sum of a (empty -> 0), using four NEON accumulators.
// The lane-parallel grouping can differ from sequential Sum by a few ULP.
func sumSIMD(a []float64) float64 {
	if len(a) == 0 {
		return 0
	}
	return sumNEON(&a[0], len(a))
}

//go:noescape
func sumNEON(a *float64, n int) float64
