// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·sumVX(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R1
	MOVD n+8(FP), R2
	VZERO V16
	VZERO V17
	VZERO V18
	VZERO V19
	loop:
	CMP R2, $8
	BLT fold
	VLM (R1), V0, V3
	VFADB V0, V16, V16
	VFADB V1, V17, V17
	VFADB V2, V18, V18
	VFADB V3, V19, V19
	ADD $64, R1
	SUB $8, R2
	BR loop
	fold:
	VFADB V17, V16, V16
	VFADB V19, V18, V18
	VFADB V18, V16, V0
	VREPG $1, V0, V1
	WFADB V0, V1, V0
	tail:
	CMP R2, $0
	BEQ done
	FMOVD (R1), F1
	FADD F1, F0
	ADD $8, R1
	SUB $1, R2
	BR tail
	done:
	FMOVD F0, ret+16(FP)
	RET

TEXT ·dotVX(SB), NOSPLIT, $0-32
	MOVD a+0(FP), R1
	MOVD b+8(FP), R3
	MOVD n+16(FP), R2
	VZERO V16
	VZERO V17
	VZERO V18
	VZERO V19
	loop:
	CMP R2, $8
	BLT fold
	VLM (R1), V0, V3
	VLM (R3), V4, V7
	VFMADB V0, V4, V16, V16
	VFMADB V1, V5, V17, V17
	VFMADB V2, V6, V18, V18
	VFMADB V3, V7, V19, V19
	ADD $64, R3
	ADD $64, R1
	SUB $8, R2
	BR loop
	fold:
	VFADB V17, V16, V16
	VFADB V19, V18, V18
	VFADB V18, V16, V0
	VREPG $1, V0, V1
	WFADB V0, V1, V0
	tail:
	CMP R2, $0
	BEQ done
	FMOVD (R1), F1
	FMOVD (R3), F2
	FMUL F2, F1
	ADD $8, R3
	FADD F1, F0
	ADD $8, R1
	SUB $1, R2
	BR tail
	done:
	FMOVD F0, ret+24(FP)
	RET

TEXT ·sqrtVX(SB), NOSPLIT, $0-24
	MOVD dst+0(FP), R1
	MOVD src+8(FP), R2
	MOVD n+16(FP), R4
	loop:
	CMP R4, $8
	BLT tail
	VLM (R2), V0, V3
	VFSQDB V0, V0
	VFSQDB V1, V1
	VFSQDB V2, V2
	VFSQDB V3, V3
	VSTM V0, V3, (R1)
	ADD $64, R1
	ADD $64, R2
	SUB $8, R4
	BR loop
	tail:
	CMP R4, $0
	BEQ done
	FMOVD (R2), F0
	FSQRT F0, F0
	FMOVD F0, (R1)
	ADD $8, R1
	ADD $8, R2
	SUB $1, R4
	BR tail
	done:
	RET

TEXT ·addVX(SB), NOSPLIT, $0-32
	MOVD dst+0(FP), R1
	MOVD a+8(FP), R2
	MOVD b+16(FP), R3
	MOVD n+24(FP), R4
	loop:
	CMP R4, $8
	BLT tail
	VLM (R2), V0, V3
	VLM (R3), V4, V7
	VFADB V4, V0, V0
	VFADB V5, V1, V1
	VFADB V6, V2, V2
	VFADB V7, V3, V3
	VSTM V0, V3, (R1)
	ADD $64, R1
	ADD $64, R2
	ADD $64, R3
	SUB $8, R4
	BR loop
	tail:
	CMP R4, $0
	BEQ done
	FMOVD (R2), F0
	FMOVD (R3), F1
	FADD F1, F0
	FMOVD F0, (R1)
	ADD $8, R1
	ADD $8, R2
	ADD $8, R3
	SUB $1, R4
	BR tail
	done:
	RET

TEXT ·subVX(SB), NOSPLIT, $0-32
	MOVD dst+0(FP), R1
	MOVD a+8(FP), R2
	MOVD b+16(FP), R3
	MOVD n+24(FP), R4
	loop:
	CMP R4, $8
	BLT tail
	VLM (R2), V0, V3
	VLM (R3), V4, V7
	VFSDB V4, V0, V0
	VFSDB V5, V1, V1
	VFSDB V6, V2, V2
	VFSDB V7, V3, V3
	VSTM V0, V3, (R1)
	ADD $64, R1
	ADD $64, R2
	ADD $64, R3
	SUB $8, R4
	BR loop
	tail:
	CMP R4, $0
	BEQ done
	FMOVD (R2), F0
	FMOVD (R3), F1
	FSUB F1, F0
	FMOVD F0, (R1)
	ADD $8, R1
	ADD $8, R2
	ADD $8, R3
	SUB $1, R4
	BR tail
	done:
	RET

TEXT ·mulVX(SB), NOSPLIT, $0-32
	MOVD dst+0(FP), R1
	MOVD a+8(FP), R2
	MOVD b+16(FP), R3
	MOVD n+24(FP), R4
	loop:
	CMP R4, $8
	BLT tail
	VLM (R2), V0, V3
	VLM (R3), V4, V7
	VFMDB V4, V0, V0
	VFMDB V5, V1, V1
	VFMDB V6, V2, V2
	VFMDB V7, V3, V3
	VSTM V0, V3, (R1)
	ADD $64, R1
	ADD $64, R2
	ADD $64, R3
	SUB $8, R4
	BR loop
	tail:
	CMP R4, $0
	BEQ done
	FMOVD (R2), F0
	FMOVD (R3), F1
	FMUL F1, F0
	FMOVD F0, (R1)
	ADD $8, R1
	ADD $8, R2
	ADD $8, R3
	SUB $1, R4
	BR tail
	done:
	RET

TEXT ·divVX(SB), NOSPLIT, $0-32
	MOVD dst+0(FP), R1
	MOVD a+8(FP), R2
	MOVD b+16(FP), R3
	MOVD n+24(FP), R4
	loop:
	CMP R4, $8
	BLT tail
	VLM (R2), V0, V3
	VLM (R3), V4, V7
	VFDDB V4, V0, V0
	VFDDB V5, V1, V1
	VFDDB V6, V2, V2
	VFDDB V7, V3, V3
	VSTM V0, V3, (R1)
	ADD $64, R1
	ADD $64, R2
	ADD $64, R3
	SUB $8, R4
	BR loop
	tail:
	CMP R4, $0
	BEQ done
	FMOVD (R2), F0
	FMOVD (R3), F1
	FDIV F1, F0
	FMOVD F0, (R1)
	ADD $8, R1
	ADD $8, R2
	ADD $8, R3
	SUB $1, R4
	BR tail
	done:
	RET

