// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·sumVSX(SB), NOSPLIT, $0-24
	MOVD a+0(FP), R3
	MOVD n+8(FP), R4
	MOVD $16, R14
	MOVD $32, R15
	MOVD $48, R16
	XXLXOR VS0, VS0, VS0
	XXLXOR VS1, VS1, VS1
	XXLXOR VS2, VS2, VS2
	XXLXOR VS3, VS3, VS3
sloop:
	CMP R4, $8
	BLT sfold
	LXVD2X (R3)(R0), VS4
	LXVD2X (R3)(R14), VS5
	LXVD2X (R3)(R15), VS6
	LXVD2X (R3)(R16), VS7
	WORD $0xf0002300 // xvadddp vs0, vs0, vs4
	WORD $0xf0212b00 // xvadddp vs1, vs1, vs5
	WORD $0xf0423300 // xvadddp vs2, vs2, vs6
	WORD $0xf0633b00 // xvadddp vs3, vs3, vs7
	ADD $64, R3
	ADD $-8, R4
	BR sloop
sfold:
	WORD $0xf0000b00 // xvadddp vs0, vs0, vs1
	WORD $0xf0421b00 // xvadddp vs2, vs2, vs3
	WORD $0xf0001300 // xvadddp vs0, vs0, vs2
	XXPERMDI VS0, VS0, $2, VS1
	WORD $0xf0000b00 // xvadddp vs0, vs0, vs1
stail:
	CMP R4, $0
	BEQ sdone
	FMOVD 0(R3), F1
	FADD F1, F0
	ADD $8, R3
	ADD $-1, R4
	BR stail
sdone:
	FMOVD F0, ret+16(FP)
	RET

TEXT ·dotVSX(SB), NOSPLIT, $0-32
	MOVD a+0(FP), R3
	MOVD b+8(FP), R5
	MOVD n+16(FP), R4
	MOVD $16, R14
	MOVD $32, R15
	MOVD $48, R16
	XXLXOR VS0, VS0, VS0
	XXLXOR VS1, VS1, VS1
	XXLXOR VS2, VS2, VS2
	XXLXOR VS3, VS3, VS3
dloop:
	CMP R4, $8
	BLT dfold
	LXVD2X (R3)(R0), VS32
	LXVD2X (R5)(R0), VS36
	LXVD2X (R3)(R14), VS33
	LXVD2X (R5)(R14), VS37
	LXVD2X (R3)(R15), VS34
	LXVD2X (R5)(R15), VS38
	LXVD2X (R3)(R16), VS35
	LXVD2X (R5)(R16), VS39
	WORD $0xf000230e // xvmaddadp vs0, vs32, vs36
	WORD $0xf0212b0e // xvmaddadp vs1, vs33, vs37
	WORD $0xf042330e // xvmaddadp vs2, vs34, vs38
	WORD $0xf0633b0e // xvmaddadp vs3, vs35, vs39
	ADD $64, R3
	ADD $64, R5
	ADD $-8, R4
	BR dloop
dfold:
	WORD $0xf0000b00 // xvadddp vs0, vs0, vs1
	WORD $0xf0421b00 // xvadddp vs2, vs2, vs3
	WORD $0xf0001300 // xvadddp vs0, vs0, vs2
	XXPERMDI VS0, VS0, $2, VS1
	WORD $0xf0000b00 // xvadddp vs0, vs0, vs1
dtail:
	CMP R4, $0
	BEQ ddone
	FMOVD 0(R3), F1
	FMOVD 0(R5), F2
	FMUL F2, F1
	FADD F1, F0
	ADD $8, R3
	ADD $8, R5
	ADD $-1, R4
	BR dtail
ddone:
	FMOVD F0, ret+24(FP)
	RET

TEXT ·sqrtVSX(SB), NOSPLIT, $0-24
	MOVD dst+0(FP), R3
	MOVD src+8(FP), R5
	MOVD n+16(FP), R4
	MOVD $16, R14
	MOVD $32, R15
	MOVD $48, R16
qloop:
	CMP R4, $8
	BLT qtail
	LXVD2X (R5)(R0), VS32
	LXVD2X (R5)(R14), VS33
	LXVD2X (R5)(R15), VS34
	LXVD2X (R5)(R16), VS35
	WORD $0xf080032f // xvsqrtdp vs36, vs32
	WORD $0xf0a00b2f // xvsqrtdp vs37, vs33
	WORD $0xf0c0132f // xvsqrtdp vs38, vs34
	WORD $0xf0e01b2f // xvsqrtdp vs39, vs35
	STXVD2X VS36, (R3)(R0)
	STXVD2X VS37, (R3)(R14)
	STXVD2X VS38, (R3)(R15)
	STXVD2X VS39, (R3)(R16)
	ADD $64, R3
	ADD $64, R5
	ADD $-8, R4
	BR qloop
qtail:
	CMP R4, $0
	BEQ qdone
	FMOVD 0(R5), F1
	FSQRT F1, F1
	FMOVD F1, 0(R3)
	ADD $8, R3
	ADD $8, R5
	ADD $-1, R4
	BR qtail
qdone:
	RET

TEXT ·addVSX(SB), NOSPLIT, $0-32
	MOVD dst+0(FP), R3
	MOVD a+8(FP), R5
	MOVD b+16(FP), R6
	MOVD n+24(FP), R4
	MOVD $16, R14
	MOVD $32, R15
	MOVD $48, R16
addloop:
	CMP R4, $8
	BLT addtail
	LXVD2X (R5)(R0), VS32
	LXVD2X (R6)(R0), VS36
	LXVD2X (R5)(R14), VS33
	LXVD2X (R6)(R14), VS37
	LXVD2X (R5)(R15), VS34
	LXVD2X (R6)(R15), VS38
	LXVD2X (R5)(R16), VS35
	LXVD2X (R6)(R16), VS39
	WORD $0xf1002307 // xvadddp vs40, vs32, vs36
	WORD $0xf1212b07 // xvadddp vs41, vs33, vs37
	WORD $0xf1423307 // xvadddp vs42, vs34, vs38
	WORD $0xf1633b07 // xvadddp vs43, vs35, vs39
	STXVD2X VS40, (R3)(R0)
	STXVD2X VS41, (R3)(R14)
	STXVD2X VS42, (R3)(R15)
	STXVD2X VS43, (R3)(R16)
	ADD $64, R3
	ADD $64, R5
	ADD $64, R6
	ADD $-8, R4
	BR addloop
addtail:
	CMP R4, $0
	BEQ adddone
	FMOVD 0(R5), F1
	FMOVD 0(R6), F2
	FADD F2, F1
	FMOVD F1, 0(R3)
	ADD $8, R3
	ADD $8, R5
	ADD $8, R6
	ADD $-1, R4
	BR addtail
adddone:
	RET

TEXT ·subVSX(SB), NOSPLIT, $0-32
	MOVD dst+0(FP), R3
	MOVD a+8(FP), R5
	MOVD b+16(FP), R6
	MOVD n+24(FP), R4
	MOVD $16, R14
	MOVD $32, R15
	MOVD $48, R16
subloop:
	CMP R4, $8
	BLT subtail
	LXVD2X (R5)(R0), VS32
	LXVD2X (R6)(R0), VS36
	LXVD2X (R5)(R14), VS33
	LXVD2X (R6)(R14), VS37
	LXVD2X (R5)(R15), VS34
	LXVD2X (R6)(R15), VS38
	LXVD2X (R5)(R16), VS35
	LXVD2X (R6)(R16), VS39
	WORD $0xf1002347 // xvsubdp vs40, vs32, vs36
	WORD $0xf1212b47 // xvsubdp vs41, vs33, vs37
	WORD $0xf1423347 // xvsubdp vs42, vs34, vs38
	WORD $0xf1633b47 // xvsubdp vs43, vs35, vs39
	STXVD2X VS40, (R3)(R0)
	STXVD2X VS41, (R3)(R14)
	STXVD2X VS42, (R3)(R15)
	STXVD2X VS43, (R3)(R16)
	ADD $64, R3
	ADD $64, R5
	ADD $64, R6
	ADD $-8, R4
	BR subloop
subtail:
	CMP R4, $0
	BEQ subdone
	FMOVD 0(R5), F1
	FMOVD 0(R6), F2
	FSUB F2, F1
	FMOVD F1, 0(R3)
	ADD $8, R3
	ADD $8, R5
	ADD $8, R6
	ADD $-1, R4
	BR subtail
subdone:
	RET

TEXT ·mulVSX(SB), NOSPLIT, $0-32
	MOVD dst+0(FP), R3
	MOVD a+8(FP), R5
	MOVD b+16(FP), R6
	MOVD n+24(FP), R4
	MOVD $16, R14
	MOVD $32, R15
	MOVD $48, R16
mulloop:
	CMP R4, $8
	BLT multail
	LXVD2X (R5)(R0), VS32
	LXVD2X (R6)(R0), VS36
	LXVD2X (R5)(R14), VS33
	LXVD2X (R6)(R14), VS37
	LXVD2X (R5)(R15), VS34
	LXVD2X (R6)(R15), VS38
	LXVD2X (R5)(R16), VS35
	LXVD2X (R6)(R16), VS39
	WORD $0xf1002387 // xvmuldp vs40, vs32, vs36
	WORD $0xf1212b87 // xvmuldp vs41, vs33, vs37
	WORD $0xf1423387 // xvmuldp vs42, vs34, vs38
	WORD $0xf1633b87 // xvmuldp vs43, vs35, vs39
	STXVD2X VS40, (R3)(R0)
	STXVD2X VS41, (R3)(R14)
	STXVD2X VS42, (R3)(R15)
	STXVD2X VS43, (R3)(R16)
	ADD $64, R3
	ADD $64, R5
	ADD $64, R6
	ADD $-8, R4
	BR mulloop
multail:
	CMP R4, $0
	BEQ muldone
	FMOVD 0(R5), F1
	FMOVD 0(R6), F2
	FMUL F2, F1
	FMOVD F1, 0(R3)
	ADD $8, R3
	ADD $8, R5
	ADD $8, R6
	ADD $-1, R4
	BR multail
muldone:
	RET

TEXT ·divVSX(SB), NOSPLIT, $0-32
	MOVD dst+0(FP), R3
	MOVD a+8(FP), R5
	MOVD b+16(FP), R6
	MOVD n+24(FP), R4
	MOVD $16, R14
	MOVD $32, R15
	MOVD $48, R16
divloop:
	CMP R4, $8
	BLT divtail
	LXVD2X (R5)(R0), VS32
	LXVD2X (R6)(R0), VS36
	LXVD2X (R5)(R14), VS33
	LXVD2X (R6)(R14), VS37
	LXVD2X (R5)(R15), VS34
	LXVD2X (R6)(R15), VS38
	LXVD2X (R5)(R16), VS35
	LXVD2X (R6)(R16), VS39
	WORD $0xf10023c7 // xvdivdp vs40, vs32, vs36
	WORD $0xf1212bc7 // xvdivdp vs41, vs33, vs37
	WORD $0xf14233c7 // xvdivdp vs42, vs34, vs38
	WORD $0xf1633bc7 // xvdivdp vs43, vs35, vs39
	STXVD2X VS40, (R3)(R0)
	STXVD2X VS41, (R3)(R14)
	STXVD2X VS42, (R3)(R15)
	STXVD2X VS43, (R3)(R16)
	ADD $64, R3
	ADD $64, R5
	ADD $64, R6
	ADD $-8, R4
	BR divloop
divtail:
	CMP R4, $0
	BEQ divdone
	FMOVD 0(R5), F1
	FMOVD 0(R6), F2
	FDIV F2, F1
	FMOVD F1, 0(R3)
	ADD $8, R3
	ADD $8, R5
	ADD $8, R6
	ADD $-1, R4
	BR divtail
divdone:
	RET

TEXT ·gemmMicro8x8VSX(SB), NOSPLIT, $0-40
	MOVD kc+0(FP), R3
	MOVD pa+8(FP), R4
	MOVD pb+16(FP), R5
	MOVD c+24(FP), R6
	MOVD ldc+32(FP), R7
	SLD $3, R7
	MOVD $16, R14
	MOVD $32, R15
	MOVD $48, R16
	XXLXOR VS0, VS0, VS0
	XXLXOR VS1, VS1, VS1
	XXLXOR VS2, VS2, VS2
	XXLXOR VS3, VS3, VS3
	XXLXOR VS4, VS4, VS4
	XXLXOR VS5, VS5, VS5
	XXLXOR VS6, VS6, VS6
	XXLXOR VS7, VS7, VS7
	XXLXOR VS8, VS8, VS8
	XXLXOR VS9, VS9, VS9
	XXLXOR VS10, VS10, VS10
	XXLXOR VS11, VS11, VS11
	XXLXOR VS12, VS12, VS12
	XXLXOR VS13, VS13, VS13
	XXLXOR VS14, VS14, VS14
	XXLXOR VS15, VS15, VS15
	XXLXOR VS16, VS16, VS16
	XXLXOR VS17, VS17, VS17
	XXLXOR VS18, VS18, VS18
	XXLXOR VS19, VS19, VS19
	XXLXOR VS20, VS20, VS20
	XXLXOR VS21, VS21, VS21
	XXLXOR VS22, VS22, VS22
	XXLXOR VS23, VS23, VS23
	XXLXOR VS24, VS24, VS24
	XXLXOR VS25, VS25, VS25
	XXLXOR VS26, VS26, VS26
	XXLXOR VS27, VS27, VS27
	XXLXOR VS28, VS28, VS28
	XXLXOR VS29, VS29, VS29
	XXLXOR VS30, VS30, VS30
	XXLXOR VS31, VS31, VS31
	CMP R3, $0
	BEQ gemmMicro8x8VSXstore
gemmMicro8x8VSXloop2:
	CMP R3, $2
	BLT gemmMicro8x8VSXone
	LXVD2X (R5)(R0), VS32
	LXVD2X (R4)(R0), VS36
	LXVD2X (R5)(R14), VS33
	LXVD2X (R4)(R14), VS37
	LXVD2X (R5)(R15), VS34
	LXVD2X (R4)(R15), VS38
	LXVD2X (R5)(R16), VS35
	LXVD2X (R4)(R16), VS39
	ADD $64, R4
	ADD $64, R5
	XXPERMDI VS36, VS36, $2, VS40
	XXPERMDI VS37, VS37, $2, VS41
	XXPERMDI VS38, VS38, $2, VS42
	XXPERMDI VS39, VS39, $2, VS43
	WORD $0xf004030e // xvmaddadp vs0, vs36, vs32
	WORD $0xf028030e // xvmaddadp vs1, vs40, vs32
	WORD $0xf0440b0e // xvmaddadp vs2, vs36, vs33
	WORD $0xf0680b0e // xvmaddadp vs3, vs40, vs33
	LXVD2X (R5)(R0), VS44
	WORD $0xf084130e // xvmaddadp vs4, vs36, vs34
	WORD $0xf0a8130e // xvmaddadp vs5, vs40, vs34
	WORD $0xf0c41b0e // xvmaddadp vs6, vs36, vs35
	WORD $0xf0e81b0e // xvmaddadp vs7, vs40, vs35
	LXVD2X (R4)(R0), VS48
	WORD $0xf105030e // xvmaddadp vs8, vs37, vs32
	WORD $0xf129030e // xvmaddadp vs9, vs41, vs32
	WORD $0xf1450b0e // xvmaddadp vs10, vs37, vs33
	WORD $0xf1690b0e // xvmaddadp vs11, vs41, vs33
	LXVD2X (R5)(R14), VS45
	WORD $0xf185130e // xvmaddadp vs12, vs37, vs34
	WORD $0xf1a9130e // xvmaddadp vs13, vs41, vs34
	WORD $0xf1c51b0e // xvmaddadp vs14, vs37, vs35
	WORD $0xf1e91b0e // xvmaddadp vs15, vs41, vs35
	LXVD2X (R4)(R14), VS49
	WORD $0xf206030e // xvmaddadp vs16, vs38, vs32
	WORD $0xf22a030e // xvmaddadp vs17, vs42, vs32
	WORD $0xf2460b0e // xvmaddadp vs18, vs38, vs33
	WORD $0xf26a0b0e // xvmaddadp vs19, vs42, vs33
	LXVD2X (R5)(R15), VS46
	WORD $0xf286130e // xvmaddadp vs20, vs38, vs34
	WORD $0xf2aa130e // xvmaddadp vs21, vs42, vs34
	WORD $0xf2c61b0e // xvmaddadp vs22, vs38, vs35
	WORD $0xf2ea1b0e // xvmaddadp vs23, vs42, vs35
	LXVD2X (R4)(R15), VS50
	WORD $0xf307030e // xvmaddadp vs24, vs39, vs32
	WORD $0xf32b030e // xvmaddadp vs25, vs43, vs32
	WORD $0xf3470b0e // xvmaddadp vs26, vs39, vs33
	WORD $0xf36b0b0e // xvmaddadp vs27, vs43, vs33
	LXVD2X (R5)(R16), VS47
	WORD $0xf387130e // xvmaddadp vs28, vs39, vs34
	WORD $0xf3ab130e // xvmaddadp vs29, vs43, vs34
	WORD $0xf3c71b0e // xvmaddadp vs30, vs39, vs35
	WORD $0xf3eb1b0e // xvmaddadp vs31, vs43, vs35
	LXVD2X (R4)(R16), VS51
	ADD $64, R4
	ADD $64, R5
	XXPERMDI VS48, VS48, $2, VS52
	XXPERMDI VS49, VS49, $2, VS53
	XXPERMDI VS50, VS50, $2, VS54
	XXPERMDI VS51, VS51, $2, VS55
	WORD $0xf010630e // xvmaddadp vs0, vs48, vs44
	WORD $0xf034630e // xvmaddadp vs1, vs52, vs44
	WORD $0xf0506b0e // xvmaddadp vs2, vs48, vs45
	WORD $0xf0746b0e // xvmaddadp vs3, vs52, vs45
	WORD $0xf090730e // xvmaddadp vs4, vs48, vs46
	WORD $0xf0b4730e // xvmaddadp vs5, vs52, vs46
	WORD $0xf0d07b0e // xvmaddadp vs6, vs48, vs47
	WORD $0xf0f47b0e // xvmaddadp vs7, vs52, vs47
	WORD $0xf111630e // xvmaddadp vs8, vs49, vs44
	WORD $0xf135630e // xvmaddadp vs9, vs53, vs44
	WORD $0xf1516b0e // xvmaddadp vs10, vs49, vs45
	WORD $0xf1756b0e // xvmaddadp vs11, vs53, vs45
	WORD $0xf191730e // xvmaddadp vs12, vs49, vs46
	WORD $0xf1b5730e // xvmaddadp vs13, vs53, vs46
	WORD $0xf1d17b0e // xvmaddadp vs14, vs49, vs47
	WORD $0xf1f57b0e // xvmaddadp vs15, vs53, vs47
	WORD $0xf212630e // xvmaddadp vs16, vs50, vs44
	WORD $0xf236630e // xvmaddadp vs17, vs54, vs44
	WORD $0xf2526b0e // xvmaddadp vs18, vs50, vs45
	WORD $0xf2766b0e // xvmaddadp vs19, vs54, vs45
	WORD $0xf292730e // xvmaddadp vs20, vs50, vs46
	WORD $0xf2b6730e // xvmaddadp vs21, vs54, vs46
	WORD $0xf2d27b0e // xvmaddadp vs22, vs50, vs47
	WORD $0xf2f67b0e // xvmaddadp vs23, vs54, vs47
	WORD $0xf313630e // xvmaddadp vs24, vs51, vs44
	WORD $0xf337630e // xvmaddadp vs25, vs55, vs44
	WORD $0xf3536b0e // xvmaddadp vs26, vs51, vs45
	WORD $0xf3776b0e // xvmaddadp vs27, vs55, vs45
	WORD $0xf393730e // xvmaddadp vs28, vs51, vs46
	WORD $0xf3b7730e // xvmaddadp vs29, vs55, vs46
	WORD $0xf3d37b0e // xvmaddadp vs30, vs51, vs47
	WORD $0xf3f77b0e // xvmaddadp vs31, vs55, vs47
	ADD $-2, R3
	BR gemmMicro8x8VSXloop2
gemmMicro8x8VSXone:
	CMP R3, $0
	BEQ gemmMicro8x8VSXstore
	LXVD2X (R5)(R0), VS32
	LXVD2X (R4)(R0), VS36
	LXVD2X (R5)(R14), VS33
	LXVD2X (R4)(R14), VS37
	LXVD2X (R5)(R15), VS34
	LXVD2X (R4)(R15), VS38
	LXVD2X (R5)(R16), VS35
	LXVD2X (R4)(R16), VS39
	XXPERMDI VS36, VS36, $2, VS40
	XXPERMDI VS37, VS37, $2, VS41
	XXPERMDI VS38, VS38, $2, VS42
	XXPERMDI VS39, VS39, $2, VS43
	WORD $0xf004030e // xvmaddadp vs0, vs36, vs32
	WORD $0xf028030e // xvmaddadp vs1, vs40, vs32
	WORD $0xf0440b0e // xvmaddadp vs2, vs36, vs33
	WORD $0xf0680b0e // xvmaddadp vs3, vs40, vs33
	WORD $0xf084130e // xvmaddadp vs4, vs36, vs34
	WORD $0xf0a8130e // xvmaddadp vs5, vs40, vs34
	WORD $0xf0c41b0e // xvmaddadp vs6, vs36, vs35
	WORD $0xf0e81b0e // xvmaddadp vs7, vs40, vs35
	WORD $0xf105030e // xvmaddadp vs8, vs37, vs32
	WORD $0xf129030e // xvmaddadp vs9, vs41, vs32
	WORD $0xf1450b0e // xvmaddadp vs10, vs37, vs33
	WORD $0xf1690b0e // xvmaddadp vs11, vs41, vs33
	WORD $0xf185130e // xvmaddadp vs12, vs37, vs34
	WORD $0xf1a9130e // xvmaddadp vs13, vs41, vs34
	WORD $0xf1c51b0e // xvmaddadp vs14, vs37, vs35
	WORD $0xf1e91b0e // xvmaddadp vs15, vs41, vs35
	WORD $0xf206030e // xvmaddadp vs16, vs38, vs32
	WORD $0xf22a030e // xvmaddadp vs17, vs42, vs32
	WORD $0xf2460b0e // xvmaddadp vs18, vs38, vs33
	WORD $0xf26a0b0e // xvmaddadp vs19, vs42, vs33
	WORD $0xf286130e // xvmaddadp vs20, vs38, vs34
	WORD $0xf2aa130e // xvmaddadp vs21, vs42, vs34
	WORD $0xf2c61b0e // xvmaddadp vs22, vs38, vs35
	WORD $0xf2ea1b0e // xvmaddadp vs23, vs42, vs35
	WORD $0xf307030e // xvmaddadp vs24, vs39, vs32
	WORD $0xf32b030e // xvmaddadp vs25, vs43, vs32
	WORD $0xf3470b0e // xvmaddadp vs26, vs39, vs33
	WORD $0xf36b0b0e // xvmaddadp vs27, vs43, vs33
	WORD $0xf387130e // xvmaddadp vs28, vs39, vs34
	WORD $0xf3ab130e // xvmaddadp vs29, vs43, vs34
	WORD $0xf3c71b0e // xvmaddadp vs30, vs39, vs35
	WORD $0xf3eb1b0e // xvmaddadp vs31, vs43, vs35
gemmMicro8x8VSXstore:
	XXPERMDI VS0, VS1, $1, VS56
	LXVD2X (R6)(R0), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R0)
	XXPERMDI VS2, VS3, $1, VS56
	LXVD2X (R6)(R14), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R14)
	XXPERMDI VS4, VS5, $1, VS56
	LXVD2X (R6)(R15), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R15)
	XXPERMDI VS6, VS7, $1, VS56
	LXVD2X (R6)(R16), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R16)
	ADD R7, R6
	XXPERMDI VS1, VS0, $1, VS56
	LXVD2X (R6)(R0), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R0)
	XXPERMDI VS3, VS2, $1, VS56
	LXVD2X (R6)(R14), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R14)
	XXPERMDI VS5, VS4, $1, VS56
	LXVD2X (R6)(R15), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R15)
	XXPERMDI VS7, VS6, $1, VS56
	LXVD2X (R6)(R16), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R16)
	ADD R7, R6
	XXPERMDI VS8, VS9, $1, VS56
	LXVD2X (R6)(R0), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R0)
	XXPERMDI VS10, VS11, $1, VS56
	LXVD2X (R6)(R14), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R14)
	XXPERMDI VS12, VS13, $1, VS56
	LXVD2X (R6)(R15), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R15)
	XXPERMDI VS14, VS15, $1, VS56
	LXVD2X (R6)(R16), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R16)
	ADD R7, R6
	XXPERMDI VS9, VS8, $1, VS56
	LXVD2X (R6)(R0), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R0)
	XXPERMDI VS11, VS10, $1, VS56
	LXVD2X (R6)(R14), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R14)
	XXPERMDI VS13, VS12, $1, VS56
	LXVD2X (R6)(R15), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R15)
	XXPERMDI VS15, VS14, $1, VS56
	LXVD2X (R6)(R16), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R16)
	ADD R7, R6
	XXPERMDI VS16, VS17, $1, VS56
	LXVD2X (R6)(R0), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R0)
	XXPERMDI VS18, VS19, $1, VS56
	LXVD2X (R6)(R14), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R14)
	XXPERMDI VS20, VS21, $1, VS56
	LXVD2X (R6)(R15), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R15)
	XXPERMDI VS22, VS23, $1, VS56
	LXVD2X (R6)(R16), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R16)
	ADD R7, R6
	XXPERMDI VS17, VS16, $1, VS56
	LXVD2X (R6)(R0), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R0)
	XXPERMDI VS19, VS18, $1, VS56
	LXVD2X (R6)(R14), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R14)
	XXPERMDI VS21, VS20, $1, VS56
	LXVD2X (R6)(R15), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R15)
	XXPERMDI VS23, VS22, $1, VS56
	LXVD2X (R6)(R16), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R16)
	ADD R7, R6
	XXPERMDI VS24, VS25, $1, VS56
	LXVD2X (R6)(R0), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R0)
	XXPERMDI VS26, VS27, $1, VS56
	LXVD2X (R6)(R14), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R14)
	XXPERMDI VS28, VS29, $1, VS56
	LXVD2X (R6)(R15), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R15)
	XXPERMDI VS30, VS31, $1, VS56
	LXVD2X (R6)(R16), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R16)
	ADD R7, R6
	XXPERMDI VS25, VS24, $1, VS56
	LXVD2X (R6)(R0), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R0)
	XXPERMDI VS27, VS26, $1, VS56
	LXVD2X (R6)(R14), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R14)
	XXPERMDI VS29, VS28, $1, VS56
	LXVD2X (R6)(R15), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R15)
	XXPERMDI VS31, VS30, $1, VS56
	LXVD2X (R6)(R16), VS57
	WORD $0xf339c307 // xvadddp vs57, vs57, vs56
	STXVD2X VS57, (R6)(R16)
	RET

