// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·sumSSE2(SB), NOSPLIT, $0-24
	MOVQ a+0(FP), AX
	MOVQ n+8(FP), CX
	XORPS X0, X0
	XORPS X1, X1
	XORPS X2, X2
	XORPS X3, X3
	block:
	CMPQ CX, $8
	JL fold
	MOVUPD (AX), X4
	MOVUPD 16(AX), X5
	MOVUPD 32(AX), X6
	MOVUPD 48(AX), X7
	ADDPD X4, X0
	ADDPD X5, X1
	ADDPD X6, X2
	ADDPD X7, X3
	ADDQ $64, AX
	SUBQ $8, CX
	JMP block
	fold:
	ADDPD X1, X0
	ADDPD X3, X2
	ADDPD X2, X0
	MOVAPS X0, X1
	UNPCKHPD X1, X1
	ADDSD X1, X0
	tail:
	TESTQ CX, CX
	JZ done
	ADDSD (AX), X0
	ADDQ $8, AX
	DECQ CX
	JMP tail
	done:
	MOVSD X0, ret+16(FP)
	RET

