package linalg

import (
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"math/cmplx"
	"strconv"
	"testing"

	"github.com/go-ndarray/ndarray"
)

// cases.json holds numpy.linalg's results on seeded inputs — every
// function, the five computation dtypes and integers, stacked, empty,
// ill-conditioned, rank-deficient, singular, defective and non-finite
// matrices, and every error numpy raises on them — generated by
// testdata/cases.py. It is embedded because the emulated CI architectures
// run the test binary from another directory.
//
//go:embed testdata/cases.json
var casesJSON []byte

type fxArray struct {
	DType string            `json:"dtype"`
	Shape []int             `json:"shape"`
	Data  []json.RawMessage `json:"data"`
}

type fxCase struct {
	Fn      string         `json:"fn"`
	Tag     string         `json:"tag"`
	Args    map[string]any `json:"args"`
	Inputs  []fxArray      `json:"inputs"`
	Outputs []fxArray      `json:"outputs"`
	Error   string         `json:"error"`
	Message string         `json:"message"`
	Kappa   float64        `json:"kappa"`
	Etol    float64        `json:"etol"`
}

func (c fxCase) String() string {
	shapes := make([][]int, len(c.Inputs))
	for i, in := range c.Inputs {
		shapes[i] = in.Shape
	}
	return fmt.Sprintf("%s[%s] %v %v", c.Fn, c.Tag, c.Args, shapes)
}

func loadCases(t *testing.T) []fxCase {
	t.Helper()
	var fx struct {
		NumPy string   `json:"numpy"`
		Cases []fxCase `json:"cases"`
	}
	if err := json.Unmarshal(casesJSON, &fx); err != nil {
		t.Fatal(err)
	}
	return fx.Cases
}

func parseNum(t *testing.T, s string) float64 {
	t.Helper()
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		t.Fatal(err)
	}
	return f
}

func fxValues(t *testing.T, raw []json.RawMessage) []complex128 {
	t.Helper()
	out := make([]complex128, len(raw))
	for i, r := range raw {
		var pair []string
		if json.Unmarshal(r, &pair) == nil {
			out[i] = complex(parseNum(t, pair[0]), parseNum(t, pair[1]))
			continue
		}
		var s string
		if err := json.Unmarshal(r, &s); err != nil {
			t.Fatal(err)
		}
		out[i] = complex(parseNum(t, s), 0)
	}
	return out
}

func fxArrayOf(t *testing.T, a fxArray) *ndarray.Array {
	t.Helper()
	dt, err := ndarray.ParseDType(a.DType)
	if err != nil {
		t.Fatal(err)
	}
	x, err := ndarray.FromSlice(fxValues(t, a.Data), a.Shape...)
	if err != nil {
		t.Fatal(err)
	}
	return x.AsType(dt)
}

// vals returns an array's elements as complex128.
func vals(a *ndarray.Array) []complex128 {
	d, _ := ndarray.Data[complex128](a.AsType(ndarray.Complex128))
	return d
}

func argFloat(args map[string]any, k string) (float64, bool) {
	v, ok := args[k]
	if !ok || v == nil {
		return 0, false
	}
	return v.(float64), true
}

func argOrd(v any) Ord {
	switch o := v.(type) {
	case nil:
		return Ord{}
	case float64:
		return P(o)
	case string:
		switch o {
		case "fro":
			return Fro
		case "nuc":
			return Nuc
		case "inf":
			return P(math.Inf(1))
		case "-inf":
			return P(math.Inf(-1))
		}
	}
	panic(fmt.Sprintf("bad ord %v", v))
}

func argAxes(v any) []int {
	switch a := v.(type) {
	case nil:
		return nil
	case float64:
		return []int{int(a)}
	}
	var out []int
	for _, x := range v.([]any) {
		out = append(out, int(x.(float64)))
	}
	return out
}

func uploOf(args map[string]any) UPLO {
	if args["uplo"] == "U" {
		return Upper
	}
	return Lower
}

func one(a *ndarray.Array, err error) ([]*ndarray.Array, error) {
	if err != nil {
		return nil, err
	}
	return []*ndarray.Array{a}, nil
}

func many(err error, a ...*ndarray.Array) ([]*ndarray.Array, error) {
	if err != nil {
		return nil, err
	}
	return a, nil
}

var qrModes = map[string]QRMode{"reduced": ModeReduced, "complete": ModeComplete, "r": ModeR, "raw": ModeRaw}

// runCase calls the Go function a case names.
func runCase(c fxCase, in []*ndarray.Array) ([]*ndarray.Array, error) {
	a := c.Args
	switch c.Fn {
	case "solve":
		return one(Solve(in[0], in[1]))
	case "inv":
		return one(Inv(in[0]))
	case "det":
		return one(Det(in[0]))
	case "slogdet":
		s, l, err := Slogdet(in[0])
		return many(err, s, l)
	case "cholesky":
		uplo := Lower
		if a["upper"] == true {
			uplo = Upper
		}
		return one(Cholesky(in[0], uplo))
	case "qr":
		mode := qrModes[a["mode"].(string)]
		q, r, err := QR(in[0], mode)
		if mode == ModeR {
			return many(err, r)
		}
		return many(err, q, r)
	case "svd":
		u, s, vh, err := SVD(in[0], a["full"].(bool))
		return many(err, u, s, vh)
	case "svdvals":
		return one(SVDVals(in[0]))
	case "eigh":
		w, v, err := Eigh(in[0], uploOf(a))
		return many(err, w, v)
	case "eigvalsh":
		return one(Eigvalsh(in[0], uploOf(a)))
	case "eig":
		w, v, err := Eig(in[0])
		return many(err, w, v)
	case "eigvals":
		return one(Eigvals(in[0]))
	case "lstsq":
		var r LstsqResult
		var err error
		if rc, ok := argFloat(a, "rcond"); ok {
			r, err = LstsqRcond(in[0], in[1], rc)
		} else {
			r, err = Lstsq(in[0], in[1])
		}
		if err != nil {
			return nil, err
		}
		rank, _ := ndarray.FromSlice([]int64{int64(r.Rank)})
		return many(nil, r.X, r.Residuals, rank, r.S)
	case "pinv":
		if rc, ok := argFloat(a, "rcond"); ok {
			return one(PinvRcond(in[0], rc))
		}
		return one(Pinv(in[0]))
	case "matrix_rank":
		if tol, ok := argFloat(a, "tol"); ok {
			return one(MatrixRankTol(in[0], tol))
		}
		return one(MatrixRank(in[0]))
	case "norm":
		keep, _ := a["keepdims"].(bool)
		return one(Norm(in[0], argOrd(a["ord"]), argAxes(a["axis"]), keep))
	case "cond":
		return one(Cond(in[0], argOrd(a["p"])))
	case "matrix_power":
		return one(MatrixPower(in[0], int(a["n"].(float64))))
	case "multi_dot":
		return one(MultiDot(in...))
	}
	panic("unknown function " + c.Fn)
}

var errKinds = map[string]error{
	"singular":  ErrSingular,
	"posdef":    ErrNotPosDef,
	"converge":  ErrNoConvergence,
	"nonfinite": ErrLinAlg,
	"shape":     ErrShape,
	"args":      ErrArgs,
}

// knownDifferences are the cases where this package deliberately departs
// from numpy, with the reason.
var knownDifferences = map[string]string{
	// numpy takes the nuclear norm of the NaN-filled "inverse" of a singular
	// matrix, whose SVD then fails; a singular matrix has condition number
	// +Inf in every norm here.
	"cond[singular] map[p:nuc]": "+Inf instead of LinAlgError",
	// numpy sums the squares unscaled and overflows; the 2-norm here is
	// rescaled (TestNormRescales checks the value).
	"norm[overflow] map[]": "1.414e200 instead of +Inf",
}

func knownDifference(c fxCase) (string, bool) {
	r, ok := knownDifferences[fmt.Sprintf("%s[%s] %v", c.Fn, c.Tag, c.Args)]
	return r, ok
}

// TestMatchesNumPy runs every fixture case: errors must be the same kind as
// numpy's; results must have numpy's dtype and shape; values are compared
// directly where they are unique, and through the defining identities where
// they are not (see checkCase).
func TestMatchesNumPy(t *testing.T) {
	cases := loadCases(t)
	checked := 0
	for i, c := range cases {
		in := make([]*ndarray.Array, len(c.Inputs))
		for j, x := range c.Inputs {
			in[j] = fxArrayOf(t, x)
		}
		got, err := runCase(c, in)
		if reason, ok := knownDifference(c); ok {
			t.Logf("case %d %v: known difference: %s", i, c, reason)
			continue
		}
		if c.Error != "" {
			if err == nil {
				t.Errorf("case %d %v: no error, numpy raises %s", i, c, c.Message)
			} else if !errors.Is(err, errKinds[c.Error]) {
				t.Errorf("case %d %v: error %v, numpy raises %s", i, c, err, c.Message)
			}
			continue
		}
		if err != nil {
			t.Errorf("case %d %v: %v", i, c, err)
			continue
		}
		if len(got) != len(c.Outputs) {
			t.Fatalf("case %d %v: %d results, numpy %d", i, c, len(got), len(c.Outputs))
		}
		ok := true
		for j, w := range c.Outputs {
			if got[j].DType().String() != w.DType || !sameShape(got[j].Shape(), w.Shape) {
				t.Errorf("case %d %v: result %d is %v %v, numpy %s %v", i, c, j, got[j].DType(), got[j].Shape(), w.DType, w.Shape)
				ok = false
			}
		}
		if !ok {
			continue
		}
		if msg := checkCase(t, c, in, got); msg != "" {
			t.Errorf("case %d %v: %s", i, c, msg)
			continue
		}
		checked++
	}
	t.Logf("%d cases, %d with values checked", len(cases), checked)
}

func sameShape(a, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// Tolerances. A value computed by a backward-stable algorithm in double
// precision is within c·n·eps·κ of the exact one, relative to the size of
// the result, where κ is the condition number of the problem: 1 for
// singular values, Hermitian eigenvalues and norms, cond(A) for solves,
// inverses and determinants. numpy's value carries the same kind of error,
// so the two may differ by twice that. c = 32 leaves room for the
// constants of the error bounds (which grow like n, not n²) without
// letting a wrong result through: an error in an algorithm shows as O(1)
// relative differences, or as residuals far above eps. A single-precision
// result is a double one rounded, so it may differ by one rounding more:
// eps32.
const tolC = 32

func isSingle(dt string) bool { return dt == "float32" || dt == "complex64" }

// valueTol is the absolute tolerance on the values of output w of a case
// with matrices of order n.
func valueTol(c fxCase, w []complex128, dt string, n int, kappa float64) float64 {
	scale := 0.0
	for _, v := range w {
		if !cmplx.IsInf(v) && !cmplx.IsNaN(v) {
			scale = math.Max(scale, cmplx.Abs(v))
		}
	}
	tol := scale * tolC * float64(max(n, 1)) * eps64 * math.Min(kappa, 1/eps64)
	if isSingle(dt) {
		tol += 2 * scale * eps32
	}
	return tol
}

// order is the largest matrix dimension of a case's first input.
func order(c fxCase) int {
	s := c.Inputs[0].Shape
	n := 1
	for _, d := range s[max(len(s)-2, 0):] {
		n = max(n, d)
	}
	return n
}

// compareValues compares got with numpy's values elementwise.
func compareValues(t *testing.T, got *ndarray.Array, want fxArray, tol float64) string {
	g, w := vals(got), fxValues(t, want.Data)
	for i := range w {
		if sameSpecial(g[i], w[i]) {
			continue
		}
		if d := cmplx.Abs(g[i] - w[i]); !(d <= tol) {
			return fmt.Sprintf("value %d = %v, numpy %v (|diff| %.3g > tol %.3g)", i, g[i], w[i], d, tol)
		}
	}
	return ""
}

// sameSpecial reports whether g and w are the same NaN or infinity.
func sameSpecial(g, w complex128) bool {
	same := func(a, b float64) bool {
		return (math.IsNaN(a) && math.IsNaN(b)) || (math.IsInf(a, 0) && a == b) || a == b
	}
	return (cmplx.IsNaN(w) || cmplx.IsInf(w)) && same(real(g), real(w)) && same(imag(g), imag(w))
}

// checkCase checks a case's values; it returns a description of the first
// failure, or "".
func checkCase(t *testing.T, c fxCase, in, got []*ndarray.Array) string {
	n := order(c)
	switch c.Fn {
	case "qr":
		if c.Args["mode"] == "raw" {
			return compareAll(t, c, got, n, c.Kappa)
		}
		return checkQR(c, in[0], got)
	case "svd":
		if msg := compareOne(t, c, got, 1, n, 1); msg != "" {
			return msg
		}
		return checkSVD(c, in[0], got)
	case "eigh":
		if msg := compareOne(t, c, got, 0, n, 1); msg != "" {
			return msg
		}
		return checkEigh(c, in[0], got)
	case "eig", "eigvals":
		return checkEig(t, c, in[0], got)
	case "svdvals", "eigvalsh", "norm":
		return compareAll(t, c, got, n, 1)
	case "lstsq":
		k := c.Kappa
		for j, kj := range []float64{k, k * k, 1, 1} {
			if msg := compareOne(t, c, got, j, n, kj); msg != "" {
				return msg
			}
		}
		return ""
	case "matrix_power":
		p := math.Abs(c.Args["n"].(float64))
		k := 1.0
		if c.Args["n"].(float64) < 0 {
			k = c.Kappa
		}
		return compareAll(t, c, got, n*int(p+1), k)
	case "cond":
		return compareAll(t, c, got, n, c.Kappa)
	}
	// solve, inv, det, slogdet, cholesky, pinv, matrix_rank, multi_dot
	return compareAll(t, c, got, n, c.Kappa)
}

func compareAll(t *testing.T, c fxCase, got []*ndarray.Array, n int, kappa float64) string {
	for j := range got {
		if msg := compareOne(t, c, got, j, n, kappa); msg != "" {
			return msg
		}
	}
	return ""
}

func compareOne(t *testing.T, c fxCase, got []*ndarray.Array, j, n int, kappa float64) string {
	w := c.Outputs[j]
	tol := valueTol(c, fxValues(t, w.Data), w.DType, n, kappa)
	if msg := compareValues(t, got[j], w, tol); msg != "" {
		return fmt.Sprintf("result %d: %s", j, msg)
	}
	return ""
}

// The identities. Matrices are taken out of the stacks as complex128 m×n
// row-major slices, and products are formed here with plain loops, apart
// from the package's own GEMM.

type cmat struct {
	m, n int
	d    []complex128
}

func (a cmat) at(i, j int) complex128 { return a.d[i*a.n+j] }

// stack splits an array (..., m, n) into its matrices.
func stack(a *ndarray.Array) []cmat {
	s := a.Shape()
	m, n := s[len(s)-2], s[len(s)-1]
	d := vals(a)
	cnt := 1
	for _, v := range s[:len(s)-2] {
		cnt *= v
	}
	out := make([]cmat, cnt)
	for i := range out {
		out[i] = cmat{m, n, d[i*m*n : (i+1)*m*n]}
	}
	return out
}

// vecs splits an array (..., k) into its vectors.
func vecs(a *ndarray.Array) [][]complex128 {
	s := a.Shape()
	k := s[len(s)-1]
	d := vals(a)
	out := make([][]complex128, 0)
	for i := 0; i+k <= len(d) && k > 0; i += k {
		out = append(out, d[i:i+k])
	}
	if k == 0 {
		cnt := 1
		for _, v := range s[:len(s)-1] {
			cnt *= v
		}
		out = make([][]complex128, cnt)
	}
	return out
}

func mul(a, b cmat) cmat {
	c := cmat{a.m, b.n, make([]complex128, a.m*b.n)}
	for i := 0; i < a.m; i++ {
		for p := 0; p < a.n; p++ {
			x := a.at(i, p)
			for j := 0; j < b.n; j++ {
				c.d[i*b.n+j] += x * b.at(p, j)
			}
		}
	}
	return c
}

func adj(a cmat) cmat {
	c := cmat{a.n, a.m, make([]complex128, len(a.d))}
	for i := 0; i < a.m; i++ {
		for j := 0; j < a.n; j++ {
			c.d[j*a.m+i] = cmplx.Conj(a.at(i, j))
		}
	}
	return c
}

// fro is the Frobenius norm.
func fro(a cmat) float64 {
	s := 0.0
	for _, v := range a.d {
		s += real(v)*real(v) + imag(v)*imag(v)
	}
	return math.Sqrt(s)
}

// diffFro is ‖a - b‖_F.
func diffFro(a, b cmat) float64 {
	s := 0.0
	for i := range a.d {
		d := a.d[i] - b.d[i]
		s += real(d)*real(d) + imag(d)*imag(d)
	}
	return math.Sqrt(s)
}

// orthErr is ‖QᴴQ - I‖_F.
func orthErr(q cmat) float64 {
	g := mul(adj(q), q)
	for i := 0; i < g.m; i++ {
		g.d[i*g.n+i]--
	}
	return fro(g)
}

// idTol is the tolerance on an identity of factors of order n with output
// dtype dt, relative to the norm of the matrix.
func idTol(n int, dt string) float64 {
	e := eps64
	if isSingle(dt) {
		e = eps32
	}
	return tolC * float64(max(n, 1)) * e
}

func checkQR(c fxCase, a *ndarray.Array, got []*ndarray.Array) string {
	dt := c.Outputs[0].DType
	n := order(c)
	rs := stack(got[len(got)-1])
	as := stack(a)
	for i, r := range rs {
		for p := 0; p < r.m; p++ {
			for q := 0; q < min(p, r.n); q++ {
				if r.at(p, q) != 0 {
					return fmt.Sprintf("R[%d] not upper triangular at (%d, %d)", i, p, q)
				}
			}
		}
		if len(got) == 1 {
			continue
		}
		q := stack(got[0])[i]
		if e := orthErr(q); e > idTol(n, dt) {
			return fmt.Sprintf("‖QᴴQ - I‖ = %.3g", e)
		}
		if e := diffFro(mul(q, r), as[i]); e > idTol(n, dt)*fro(as[i]) {
			return fmt.Sprintf("‖A - QR‖ = %.3g, ‖A‖ = %.3g", e, fro(as[i]))
		}
	}
	return ""
}

func checkSVD(c fxCase, a *ndarray.Array, got []*ndarray.Array) string {
	dt := c.Outputs[0].DType
	n := order(c)
	us, ss, vs := stack(got[0]), vecs(got[1]), stack(got[2])
	for i, x := range stack(a) {
		u, vh := us[i], vs[i]
		if e := orthErr(u); e > idTol(n, dt) {
			return fmt.Sprintf("‖UᴴU - I‖ = %.3g", e)
		}
		if e := orthErr(adj(vh)); e > idTol(n, dt) {
			return fmt.Sprintf("‖VhVhᴴ - I‖ = %.3g", e)
		}
		k := min(x.m, x.n)
		us := cmat{x.m, k, make([]complex128, x.m*k)}
		for r := 0; r < x.m; r++ {
			for j := 0; j < k; j++ {
				us.d[r*k+j] = u.at(r, j) * ss[i][j]
			}
		}
		if e := diffFro(mul(us, cmat{k, x.n, vh.d[:k*x.n]}), x); e > idTol(n, dt)*fro(x) {
			return fmt.Sprintf("‖A - USVh‖ = %.3g, ‖A‖ = %.3g", e, fro(x))
		}
	}
	return ""
}

// hermitianOf completes x from the triangle uplo selects, as the
// eigensolver reads it.
func hermitianOf(x cmat, upper bool) cmat {
	h := cmat{x.m, x.n, make([]complex128, len(x.d))}
	for i := 0; i < x.n; i++ {
		for j := 0; j < x.n; j++ {
			src := x.at(i, j)
			if (j > i) != upper && i != j {
				src = cmplx.Conj(x.at(j, i))
			}
			if i == j {
				src = complex(real(src), 0)
			}
			h.d[i*x.n+j] = src
		}
	}
	return h
}

func checkEigh(c fxCase, a *ndarray.Array, got []*ndarray.Array) string {
	dt := c.Outputs[1].DType
	n := order(c)
	ws, vs := vecs(got[0]), stack(got[1])
	for i, x := range stack(a) {
		h := hermitianOf(x, c.Args["uplo"] == "U")
		v := vs[i]
		if e := orthErr(v); e > idTol(n, dt) {
			return fmt.Sprintf("‖VᴴV - I‖ = %.3g", e)
		}
		vw := cmat{v.m, v.n, make([]complex128, len(v.d))}
		for r := 0; r < v.m; r++ {
			for j := 0; j < v.n; j++ {
				vw.d[r*v.n+j] = v.at(r, j) * ws[i][j]
			}
		}
		if e := diffFro(mul(h, v), vw); e > idTol(n, dt)*math.Max(fro(h), math.SmallestNonzeroFloat64) {
			return fmt.Sprintf("‖AV - VW‖ = %.3g, ‖A‖ = %.3g", e, fro(h))
		}
		for j := 1; j < len(ws[i]); j++ {
			if real(ws[i][j]) < real(ws[i][j-1]) {
				return "eigenvalues not ascending"
			}
		}
	}
	return ""
}

func checkEig(t *testing.T, c fxCase, a *ndarray.Array, got []*ndarray.Array) string {
	dt := c.Outputs[0].DType
	n := order(c)
	want := vecs(fxArrayOf(t, c.Outputs[0]))
	ws := vecs(got[0])
	realInput := !isComplexDType(c.Inputs[0].DType)
	for i, x := range stack(a) {
		// Eigenvalues: each of numpy's matched to the nearest unused one.
		tol := math.Max(c.Etol, idTol(n, "float64")*fro(x))
		if isSingle(dt) {
			tol += 2 * eps32 * maxAbs(want[i])
		}
		used := make([]bool, len(ws[i]))
		for _, w := range want[i] {
			best, bd := -1, math.Inf(1)
			for j, g := range ws[i] {
				if d := cmplx.Abs(g - w); !used[j] && d < bd {
					best, bd = j, d
				}
			}
			if !(bd <= tol) {
				return fmt.Sprintf("eigenvalue %v of numpy: nearest is %.3g away (tol %.3g)", w, bd, tol)
			}
			used[best] = true
		}
		if realInput {
			for j := 0; j < len(ws[i]); j++ {
				if imag(ws[i][j]) > 0 {
					if j+1 == len(ws[i]) || ws[i][j+1] != cmplx.Conj(ws[i][j]) {
						return fmt.Sprintf("eigenvalue %d %v not followed by its conjugate", j, ws[i][j])
					}
					j++
				}
			}
		}
		if len(got) == 1 {
			continue
		}
		v := stack(got[1])[i]
		av := mul(x, v)
		for j := 0; j < v.n; j++ {
			nrm, res, big := 0.0, 0.0, 0.0
			for r := 0; r < v.m; r++ {
				z := v.at(r, j)
				nrm += real(z)*real(z) + imag(z)*imag(z)
				big = math.Max(big, cmplx.Abs(z))
				d := av.at(r, j) - z*ws[i][j]
				res += real(d)*real(d) + imag(d)*imag(d)
			}
			if math.Abs(math.Sqrt(nrm)-1) > idTol(n, dt) {
				return fmt.Sprintf("eigenvector %d has norm %v", j, math.Sqrt(nrm))
			}
			// The residual of a computed eigenpair is backward-stable:
			// small relative to ‖A‖ even for ill-conditioned eigenvalues.
			if r := math.Sqrt(res); r > idTol(n, dt)*fro(x) {
				return fmt.Sprintf("‖Av - λv‖ = %.3g for eigenvector %d, ‖A‖ = %.3g", r, j, fro(x))
			}
			hasReal := false
			for r := 0; r < v.m; r++ {
				z := v.at(r, j)
				if imag(z) == 0 && cmplx.Abs(z) >= big*(1-1e-6) {
					hasReal = true
				}
			}
			if !hasReal {
				return fmt.Sprintf("eigenvector %d: its largest component is not real", j)
			}
			if realInput && imag(ws[i][j]) > 0 {
				for r := 0; r < v.m; r++ {
					if v.at(r, j+1) != cmplx.Conj(v.at(r, j)) {
						return fmt.Sprintf("eigenvectors %d and %d are not conjugate", j, j+1)
					}
				}
			}
		}
	}
	return ""
}

func isComplexDType(dt string) bool { return dt == "complex64" || dt == "complex128" }

func maxAbs(x []complex128) float64 {
	m := 0.0
	for _, v := range x {
		m = math.Max(m, cmplx.Abs(v))
	}
	return m
}
