# Generates random/zz_libm_tables.go: the double-double constants of the
# correctly rounded log/exp in libm.go, from mpmath at 300 bits:
#   uv run --with mpmath python random/testdata/libm_tables.py > random/zz_libm_tables.go
import mpmath
mpmath.mp.prec = 300

def dd(v):
    hi = float(v)
    lo = float(v - mpmath.mpf(hi))
    return hi, lo

def lit(x):
    return float.hex(x)

out = ["// Code generated by testdata/libm_tables.py (mpmath, 300 bits). DO NOT EDIT.", "", "package random", ""]
h, l = dd(mpmath.log(2))
out.append(f"const (\n\tln2Hi = {h!r}\n\tln2Lo = {l!r}\n)\n")
x = mpmath.log(2) / 64
a = float(x); b = float(x - a); c = float(x - a - b)
out.append(f"// ln2/64 as three doubles.\nconst (\n\tln2by64A = {a!r}\n\tln2by64B = {b!r}\n\tln2by64C = {c!r}\n)\n")
out.append("// logTab[j-45] is log(j/64) for j in [45, 91], as hi, lo.")
out.append("var logTab = [47][2]float64{")
for j in range(45, 92):
    h, l = dd(mpmath.log(mpmath.mpf(j) / 64))
    out.append(f"\t{{{h!r}, {l!r}}},")
out.append("}\n")
out.append("// exp2Tab[j] is 2**(j/64) for j in [0, 64), as hi, lo.")
out.append("var exp2Tab = [64][2]float64{")
for j in range(64):
    h, l = dd(mpmath.power(2, mpmath.mpf(j) / 64))
    out.append(f"\t{{{h!r}, {l!r}}},")
out.append("}")
print("\n".join(out))
